import { readFileSync } from "node:fs";
import { join } from "node:path";
import Link from "next/link";
import type { ReactNode } from "react";
import { dlRoadmap } from "../roadmap";
import { BatchLab, DecayLab, EarlyStoppingLab, HistoryLab, ScheduleLab, TrajectoryLab } from "./Labs";
import "./Week3.css";

const questions = [
  ["What does the optimizer receive from backpropagation?", "Gradients of the chosen objective with respect to parameters. The optimizer combines these with its learning rate, state, and update rules. Backpropagation itself does not choose the training strategy."],
  ["Is every minibatch gradient an unbiased estimate?", "For a fixed parameter value and uniformly sampled examples, the average of per-example gradients is an unbiased estimate of the empirical mean gradient. Different sampling or weighting schemes can change that property. Batch-dependent operations, such as BatchNorm, also complicate the simple per-example decomposition."],
  ["Why does curvature affect the learning rate?", "For a positive-definite quadratic with largest curvature λmax, plain gradient descent converges when 0 < η < 2/λmax. The steepest direction limits the step size, which can make progress slow in flatter directions. A nonconvex network is more complicated than this local illustration."],
  ["How can identical current gradients give different momentum updates?", "The stored velocity depends on previous gradients. With v = βv_previous + g, two runs with the same g but different v_previous produce different updates. Identical gradients do not imply identical optimizer state."],
  ["How do RMSProp and Adam differ?", "RMSProp rescales a coordinate using a moving average of squared gradients. Adam also maintains a moving average of gradients and corrects the zero-initialization bias in its first and second moment estimates. Exact defaults and options matter."],
  ["Why does Adam need bias correction?", "Starting its moving averages at zero reduces their early magnitude. Under a stationary moment model, dividing by 1 − β^t corrects that initialization bias. It does not remove dataset bias or guarantee a good update."],
  ["Is AdamW simply Adam with an L2 term added to the loss?", "No. A loss penalty contributes to the gradient and enters Adam’s adaptive moment calculations. AdamW applies parameter shrinkage separately. For plain SGD without momentum, a suitably scaled L2 penalty and decay can give the same update; that equivalence does not carry over unchanged to adaptive methods."],
  ["Does a learning-rate schedule calculate gradients?", "No. It changes the rate used by future optimizer steps. Some schedules depend on a training-time index; reduce-on-plateau depends on a monitored metric. The optimizer and gradient calculation still have their own jobs."],
  ["Do low training loss and high validation loss prove overfitting?", "They suggest a generalization problem, but distribution mismatch, a flawed split, or mismatched evaluation behavior may also contribute. Inspect the pipeline and compare controlled changes before choosing a remedy."],
  ["Which model should early stopping return?", "The checkpoint with the best validation behavior according to the specified improvement rule, not necessarily the final logged epoch. Validation has selected training duration. The final test set must stay outside that selection."],
  ["Does model.eval() disable autograd?", "No. It changes modules such as Dropout and BatchNorm into evaluation behavior. Use no_grad() or inference_mode() separately when gradients are unnecessary."],
  ["What makes an optimizer comparison fair?", "Use a common task, split, architecture, loss, and initialization policy; give each method an appropriate validation-based tuning budget. Report trajectories, cost, stopping rules, and variation across seeds. Evaluate the chosen procedure on held-out test data after selection."],
];

function Topic({ id, number, title, slides, children }: { id: string; number: string; title: string; slides: string; children: ReactNode }) {
  return <section className="w3-topic" id={id} aria-labelledby={id + "-title"}><header><span className="w3-eyebrow">CONCEPT {number} · LECTURE SLIDES {slides}</span><h2 id={id + "-title"}>{title}</h2></header>{children}</section>;
}
function Formula({ children }: { children: ReactNode }) {
  return <div className="w3-formula">{children}</div>;
}
function Table({ label, children }: { label: string; children: ReactNode }) {
  return <div className="w3-table-scroll" tabIndex={0} role="region" aria-label={label}>{children}</div>;
}

export default function Week3() {
  const example = readFileSync(join(process.cwd(), "public/examples/dl-week-3.py"), "utf8");
  return <article id="week-3" className="week-block w3" aria-labelledby="week-3-title">
    <header className="w3-hero"><span className="w3-eyebrow">DEEP LEARNING / TURN GRADIENTS INTO PROGRESS</span><h1 id="week-3-title">Week 3 — {dlRoadmap[3].title}</h1><p>Week 2 asked whether useful gradients can reach the early layers. Now ask what happens after those gradients arrive: how does an optimizer move, and does the resulting model work on new data?</p><p className="w3-source-note">Based on your Algorithms II <strong>Week 4</strong> slide deck, <code>algo2-week4.pptx</code>. This site starts at Week 0, so the matching lesson is Week 3.</p>
      <div className="w3-hero-flow" aria-label="Training loop: prediction, loss, gradients, optimizer update, next prediction.">{["Prediction", "Loss", "Gradients", "Update"].map((step, i) => <div key={step}><span>{String(i + 1).padStart(2, "0")}</span><strong>{step}</strong></div>)}</div>
      <nav className="w3-navigation" aria-label="Week 3 sections"><a href="#w3-batches">Batch noise ↓</a><a href="#w3-geometry">Optimizer paths ↓</a><a href="#w3-optimizers">Inside the update ↓</a><a href="#w3-regularization">Regularization ↓</a><a href="#w3-schedules">Schedules ↓</a><a href="#w3-evidence">Generalization ↓</a><a href="#w3-checkpoints">Early stopping ↓</a><a href="#w3-experiment">Run the example ↓</a></nav>
    </header>
    <aside className="w3-callout"><strong>The driving question</strong><p>Why can models supplied with the same gradients take different updates, and why is a lower training loss not enough to establish better generalization?</p></aside>
    <div className="w3-goals"><span className="w3-eyebrow">BY THE END OF THIS WEEK</span><ul><li>Distinguish the source of a gradient from the rule that turns it into an update.</li><li>Trace momentum, RMSProp, and Adam’s state through numerical examples.</li><li>Explain why AdamW, dropout, scheduling, and early stopping change different parts of training.</li><li>Design a controlled comparison using validation for selection and a reserved test set for final evaluation.</li></ul></div>

    <Topic id="w3-batches" number="01" title="A gradient is an estimate of what to change." slides="2–4">
      <p>For a dataset of N observations, the empirical objective is the average of the individual losses. Full-batch gradient descent uses every observation for one update. Single-example SGD uses one observation; minibatch SGD averages a smaller group. In practice, “SGD” often refers to the minibatch version too.</p>
      <Formula>L(θ) = (1/N) Σᵢ ℓᵢ(θ)<br />Full gradient: g = (1/N) Σᵢ ∇ℓᵢ(θ)<br />Batch estimate: gB = (1/|B|) Σᵢ∈B ∇ℓᵢ(θ)</Formula>
      <Table label="Full batch, stochastic, and minibatch gradient descent"><table><thead><tr><th scope="col">Method</th><th scope="col">Observations per update</th><th scope="col">Trade-off</th></tr></thead><tbody><tr><th scope="row">Full batch</th><td>All N</td><td>Exact gradient of this empirical objective at the current parameters, but potentially costly per update.</td></tr><tr><th scope="row">Single-example SGD</th><td>1</td><td>Frequent, inexpensive updates with high sampling variability.</td></tr><tr><th scope="row">Minibatch SGD</th><td>A batch of B</td><td>Uses vectorized hardware efficiently while retaining sampling variability.</td></tr></tbody></table></Table>
      <p>Under uniform sampling, a mean of per-example gradients is unbiased for the empirical mean gradient at a fixed parameter value. Larger batches generally reduce its sampling variance. This statement needs care with nonuniform sampling or operations whose outputs depend on the whole batch.</p><p>Noise changes the optimization path. It can help a run move through some flat or saddle-like regions, but can also slow convergence. Full-batch does not mean “correct about the population,” and noisy does not automatically mean “generalizes better.”</p>
      <BatchLab />
    </Topic>

    <Topic id="w3-geometry" number="02" title="A step size has to fit the geometry." slides="5–6">
      <p>Backpropagation gives local sensitivity. Plain gradient descent multiplies that gradient by a learning rate and moves in the opposite direction. A very small rate can make progress hard to see; a large rate can oscillate or diverge.</p><Formula>θnext = θ − η∇L(θ)<br />Quadratic example: L(θ) = ½θᵀAθ, ∇L = Aθ<br />For positive-definite A: 0 &lt; η &lt; 2/λmax(A) gives convergence of plain gradient descent.</Formula>
      <p>When one direction is much steeper than another, a single rate becomes a compromise. A rate small enough for the steep direction may make the flatter direction painfully slow. The quadratic below makes that conditioning visible without pretending to reproduce a complete neural-network loss surface.</p>
      <TrajectoryLab />
    </Topic>

    <Topic id="w3-optimizers" number="03" title="State turns the same gradient into a different update." slides="7–13">
      <div className="w3-concept-grid"><div><h3>Momentum: remember direction</h3><p>The velocity accumulates past gradients. Persistent signs reinforce each other; alternating signs can partially cancel. State can carry a run forward even when the current gradient becomes small.</p><Formula>vₜ = βvₜ₋₁ + gₜ<br />θₜ = θₜ₋₁ − ηvₜ</Formula><p className="w3-small">This unnormalized velocity convention matches the slides and ordinary PyTorch SGD momentum with zero dampening. Other presentations put a factor of (1 − β) on gₜ and use a correspondingly different scale.</p></div><div><h3>RMSProp: remember scale</h3><p>A running average of squared gradients rescales each coordinate. A large second-moment estimate makes the multiplier on that coordinate’s current gradient smaller. This concerns the effective multiplier, not a guarantee that its absolute update is smaller than every other coordinate’s.</p><Formula>sₜ = αsₜ₋₁ + (1 − α)gₜ²<br />θₜ = θₜ₋₁ − ηgₜ / (√sₜ + ε)</Formula></div></div>
      <h3>Adam: direction and scale, with bias correction</h3><p>Adam tracks both first and second moments. Starting them at zero depresses early estimates. The correction compensates for that initialization under a stationary moment model; it is not a correction for biased training data.</p>
      <Formula>mₜ = β₁mₜ₋₁ + (1 − β₁)gₜ<br />vₜ = β₂vₜ₋₁ + (1 − β₂)gₜ²<br />m̂ₜ = mₜ / (1 − β₁ᵗ), v̂ₜ = vₜ / (1 − β₂ᵗ)<br />θₜ = θₜ₋₁ − ηm̂ₜ / (√v̂ₜ + ε)</Formula>
      <p>All squared operations and divisions above are coordinatewise. For a constant first gradient g, Adam’s first corrected estimates are g and g². Its resulting first step is approximately −η·sign(g) when g is not tiny relative to ε.</p><HistoryLab />
      <p className="w3-source">Implementation references: <a href="https://docs.pytorch.org/docs/stable/generated/torch.optim.SGD.html">PyTorch SGD</a>, <a href="https://docs.pytorch.org/docs/stable/generated/torch.optim.RMSprop.html">RMSprop</a>, and the <a href="https://arxiv.org/abs/1412.6980">Adam paper</a>.</p>
    </Topic>

    <Topic id="w3-regularization" number="04" title="Regularizers change different mechanisms." slides="14–15, 21">
      <p>Dropout, weight decay, and early stopping can all influence generalization, but they do different things. Use them to test a hypothesis about the training problem, rather than treating them as interchangeable switches.</p>
      <Table label="Distinct regularization mechanisms"><table><thead><tr><th scope="col">Method</th><th scope="col">What changes</th><th scope="col">What to check</th></tr></thead><tbody><tr><th scope="row">Dropout</th><td>Activations are randomly suppressed during training; inverted dropout rescales survivors.</td><td>Use train() for training and eval() for evaluation. Dropout does not directly repair every optimization failure.</td></tr><tr><th scope="row">Weight decay</th><td>Parameter magnitudes shrink during updates.</td><td>Check whether shrinkage is coupled to the gradient or applied separately. Consider which parameters should receive decay.</td></tr><tr><th scope="row">Early stopping</th><td>Validation behavior selects a training duration and checkpoint.</td><td>Restore the selected weights and keep test data outside the stopping decision.</td></tr></tbody></table></Table>
      <h3>Why AdamW is not simply “Adam plus L2”</h3><p>With the convention Ltotal = Ldata + (λ/2)‖w‖², the penalty contributes λw to the gradient. For plain SGD without momentum, its update equals a shrinkage term plus the ordinary data-gradient update. With Adam, that added gradient also changes the moment estimates and adaptive rescaling.</p><Formula>Plain SGD with this L2 penalty:<br />wnew = w − η(gdata + λw) = (1 − ηλ)w − ηgdata<br /><br />AdamW:<br />wnew = (1 − ηλ)w + adaptive update computed from gdata</Formula>
      <p>AdamW decouples shrinkage from the adaptive update. A learning-rate schedule also changes the amount of shrinkage per step through ηλ. Decay strengths therefore need tuning within the actual optimizer and schedule configuration.</p><DecayLab /><p className="w3-source">Read the <a href="https://arxiv.org/abs/1711.05101">decoupled weight decay paper</a> and <a href="https://docs.pytorch.org/docs/stable/generated/torch.optim.AdamW.html">PyTorch AdamW documentation</a>.</p>
    </Topic>

    <Topic id="w3-schedules" number="05" title="Plan how the response changes over time." slides="16–17">
      <p>A schedule changes the learning rate used by later optimizer steps. Step decay encodes milestones, exponential decay reduces the rate proportionally, and cosine decay moves smoothly toward a lower endpoint. Warmup increases the rate during the beginning of a run before another schedule takes over.</p><p>Reduce-on-plateau instead responds to an observed metric. A plateau alone does not prove that a rate reduction is the right fix: inspect the data, objective, and training behavior too. Schedules do not replace the optimizer or calculate gradients.</p><ScheduleLab />
      <p className="w3-source">API details and stepping order: <a href="https://docs.pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate">PyTorch learning-rate scheduling</a>.</p>
    </Topic>

    <Topic id="w3-evidence" number="06" title="Optimization and generalization ask different questions." slides="18–20, 23–24">
      <p>Optimization asks whether the training procedure improves its objective. Generalization asks whether performance transfers to relevant unseen data. A flexible model can lower training loss by fitting real structure, noise, or collection artifacts; the training curve alone cannot distinguish those explanations.</p>
      <Table label="Interpret training and validation evidence"><table><thead><tr><th scope="col">Observed pattern</th><th scope="col">Possible causes</th><th scope="col">A useful next check</th></tr></thead><tbody>
        <tr><th scope="row">Both losses stay high</th><td>Insufficient features or capacity, failed optimization, or a data/objective problem</td><td>Try overfitting a tiny clean batch; inspect inputs, labels, gradients, and the output/loss pairing.</td></tr>
        <tr><th scope="row">Training improves; validation worsens</th><td>Overfitting or distribution mismatch; possibly inconsistent evaluation</td><td>Check the split and train/eval modes, then compare regularization or stopping choices using validation.</td></tr>
        <tr><th scope="row">Loss is erratic or non-finite</th><td>Unstable updates, excessive step size, numerical problems, or pipeline issues</td><td>Inspect finite values and gradient norms; change one factor at a time.</td></tr>
        <tr><th scope="row">Progress is very slow</th><td>A small learning rate, poor conditioning, or weak signal</td><td>Compare a short controlled rate sweep and optimizer trajectories.</td></tr>
        <tr><th scope="row">Training and validation both improve</th><td>A useful fit on these development samples</td><td>Confirm with the reserved final evaluation and report sampling uncertainty.</td></tr>
      </tbody></table></Table>
      <p>Bias describes systematic error across possible training samples; variance describes sensitivity to which sample was used. Capacity can affect both, but a single pair of loss curves is not a direct measurement of that decomposition. A more expressive model can still perform poorly because its optimization failed.</p>
      <aside className="w3-callout"><strong>The test set can become hidden training feedback.</strong><p>If you repeatedly inspect test scores and use them to keep changing the model, the test set has become part of selection. Use validation for choices; reserve final test reporting until the procedure is fixed.</p></aside>
    </Topic>

    <Topic id="w3-checkpoints" number="07" title="Early stopping selects a checkpoint." slides="21–22">
      <p>At each epoch, evaluate a validation metric. Save a snapshot when it improves according to the chosen rule, reset the waiting counter, and otherwise increment the counter. Stop when patience is exhausted, then restore the selected snapshot.</p><p>A snapshot must not be a mutable reference that changes as training continues. In PyTorch, copy the state dictionary when retaining it in memory. Saving model state is sufficient for this inference comparison; exact training resumption requires more state.</p><EarlyStoppingLab />
      <p className="w3-source">Checkpoint handling: <a href="https://docs.pytorch.org/tutorials/beginner/saving_loading_models.html">PyTorch’s saving and loading guide</a>.</p>
    </Topic>

    <Topic id="w3-experiment" number="08" title="Compare configured methods, not arbitrary defaults." slides="25–27">
      <Table label="A controlled optimizer study"><table><thead><tr><th scope="col">Keep comparable</th><th scope="col">Tune using validation</th><th scope="col">Report</th></tr></thead><tbody><tr><td>Task, split, input representation, architecture, loss, and initialization policy</td><td>Learning rate and optimizer-specific state settings</td><td>Training and validation trajectories</td></tr><tr><td>Seed policy, batch-order policy, stopping rules, and a declared resource budget</td><td>Weight decay and schedule choices, with an explicit tuning budget</td><td>Epochs, update counts or time, variation across seeds, and the final held-out result</td></tr></tbody></table></Table>
      <p>The example below compares momentum SGD and AdamW, with two learning rates per method and two seeds. It uses the lecture’s 20 → 64 → 1 architecture with ReLU and dropout. Each seed starts from the same initial parameters and batch-order generator across configurations.</p><p>The data and split are fixed, and normalization statistics come only from training rows. Both methods start with zero weight decay so a later decay experiment can be explicit. Training and validation curves are measured in eval mode with dropout disabled, making their loss definitions comparable.</p>
      <div className="w3-experiment-facts"><span>600 synthetic rows</span><span>360 train / 120 validation / 120 test</span><span>4 configurations × 2 seeds</span><span>50-epoch maximum / patience 6</span></div>
      <p>Choose a configuration by mean validation loss across the two seeds. The first seed is declared in advance for the final test report, so the script does not choose whichever seed happened to score best. This small study illustrates a procedure; it cannot establish a universal optimizer ranking.</p>
      <div className="w3-code"><div className="w3-code-heading"><span>RUN LOCALLY · PYTHON / PYTORCH</span><span>CPU · NO DATA DOWNLOAD</span></div><pre tabIndex={0} aria-label="Setup and run commands"><code>{"python -m venv .venv\n# Activate the environment for your operating system.\npython -m pip install torch\npython dl-week-3.py"}</code></pre></div>
      <a className="w3-download" href="/examples/dl-week-3.py" download="dl-week-3.py">Download the complete Python example ↓</a>
      <details className="w3-detail w3-example"><summary>Read the complete training and evaluation script</summary><div className="w3-code"><pre tabIndex={0} aria-label="Complete PyTorch optimizer comparison"><code>{example}</code></pre></div></details>
      <h3>Inspect the outputs</h3><ul><li><code>dl-week-3-curves.csv</code>: open in Excel, filter to one optimizer/rate/seed, and plot epoch against the two loss columns.</li><li><code>dl-week-3-summary.csv</code>: compare retained validation performance, selected epochs, total epochs, and measured runtime.</li><li><code>dl-week-3.pt</code>: model weights and fitted input statistics for inference. The script reloads it and checks that predictions match.</li><li>The final test loss and accuracy appear only after configuration selection. Keep that result out of subsequent tuning decisions.</li></ul>
      <p className="w3-small">Package versions and hardware can affect timing and exact numerical results. The script reports its PyTorch version. The examples and browser experiments are study companions to the supplied lecture, not measured results from its slides.</p>
    </Topic>

    <section className="w3-topic" id="w3-practice" aria-labelledby="w3-practice-title"><span className="w3-eyebrow">YOUR TURN / PREDICT, RUN, EXPLAIN</span><h2 id="w3-practice-title">Make the mechanism visible.</h2><ol className="w3-exercises"><li><strong>Enumerate the noise.</strong> Set θ = 2 in the batch demo. Explain why the full gradient is zero while individual minibatches need not be. Confirm that all equally likely batch estimates average to zero.</li><li><strong>Trace the lecture arithmetic.</strong> With gradients −3, −2, −1, η = 0.1, and β = 0.9, calculate the three momentum velocities and parameter values before checking the table. Repeat the squared-gradient trace for RMSProp with gradients 4, 2, 1.</li><li><strong>Find the stability boundary.</strong> Use SGD with curvature 20. Compare rates 0.08, 0.10, and 0.12. Explain the behavior of the steep coordinate from its multiplier, 1 − ηc.</li><li><strong>Separate two decay mechanisms.</strong> Set the data gradient to zero. Compare the first Adam + L2 and AdamW steps as λ changes, keeping the same rate. State which formula convention you used.</li><li><strong>Write a comparison before running it.</strong> Choose an experiment with a fixed split and a stated tuning budget. Use the CSV curves to report what happened, including a result that challenges your initial expectation.</li></ol></section>
    <section className="w3-topic w3-review" id="w3-review" aria-labelledby="w3-review-title"><span className="w3-eyebrow">EXPLAIN IT WITHOUT THE CODE</span><h2 id="w3-review-title">Week 3 interview questions</h2><p>Try answering aloud before opening the explanation.</p>{questions.map(([question, answer], i) => <details className="w3-detail" key={question}><summary><span>{String(i + 1).padStart(2, "0")}</span>{question}</summary><p>{answer}</p></details>)}</section>
    <section className="w3-topic" aria-labelledby="w3-research-title"><span className="w3-eyebrow">PEOPLE BEHIND THE IDEAS</span><h2 id="w3-research-title">Research connections</h2><div className="w3-concept-grid"><article><h3>Kingma &amp; Ba · 2014</h3><p>Adam combines adaptive first- and second-moment estimates with bias correction.</p><a href="https://arxiv.org/abs/1412.6980">Adam: A Method for Stochastic Optimization ↗</a></article><article><h3>Loshchilov &amp; Hutter · 2017 preprint</h3><p>Decoupled weight decay distinguishes the parameter-shrinkage step from adaptive loss-gradient updates.</p><a href="https://arxiv.org/abs/1711.05101">Decoupled Weight Decay Regularization ↗</a></article></div></section>
    <aside className="w3-callout"><strong>The standard you want</strong><p>Explain an optimizer from its state and update rule, distinguish training progress from evidence of generalization, and justify a model-selection procedure that keeps its final evaluation independent.</p></aside>
    <div className="w3-next"><span className="w3-eyebrow">NEXT / FROM GENERIC VECTORS TO SPATIAL STRUCTURE</span><p>The next week introduces locality, shared patterns, and convolutional neural networks, matching the lecture’s bridge to course Week 5.</p><Link href="/dl/week-4">Preview Week 4: Convolutional Neural Networks →</Link></div>
    <Link className="week-back-to-map" href="/dl#week-3">Back to the learning map ↑</Link>
  </article>;
}

