import type { Metadata } from "next";
import Link from "next/link";
import ScienceFlow from "../ScienceFlow";
import BiologyUniverse from "./BiologyUniverse";
import ChapterNav from "./ChapterNav";
import { DiffusionLab, InheritanceLab, PopulationLab } from "./Labs";
import { branches, ideas } from "./universe";
import { bridges, chapters, learningSteps, levelsOfLife, openQuestions, resources } from "./content";

export const metadata: Metadata = {
  title: "Biology: From Molecules to Living Systems — Layerchecklist",
  description: `Explore ${ideas.length} biological ideas across ${branches.length} branches, with lessons on cells, genetics, evolution, ecology and computation, plus three interactive models.`,
};
function Heading({ number, title, children }: { number: string; title: string; children?: React.ReactNode }) {
  return <header className="bio-chapter-heading"><span className="bio-eyebrow">CHAPTER {number}</span><h2>{title}</h2>{children}</header>;
}
export default function BiologyPage() {
  return <main className="bio-page">
    <Link className="bio-back" href="/#biology">← Back to the learning path</Link>
    <ScienceFlow current="biology" />
    <header className="bio-hero"><div><p className="bio-eyebrow">BIOLOGY / THE THIRD FOUNDATION</p><h1>Matter becomes<br /><span>a living system.</span></h1><p className="bio-lead">Math gives us a language for patterns. Physics describes the constraints on matter and energy. Biology asks how living systems maintain themselves, pass on information, evolve and interact—within those constraints, with a history that matters.</p><div className="bio-hero-actions"><a className="bio-button" href="#atlas">Explore the biology atlas ↓</a><a href="#life">Start with life ↗</a></div></div><div className="bio-hero-stats"><div><strong>{ideas.length}</strong><span>ideas in the atlas</span><small>From molecules to ecosystems</small></div><div><strong>{branches.length}</strong><span>connected branches</span><small>Different scales of the living world</small></div><div><strong>{chapters.length}</strong><span>chapters</span><small>A path with room to explore</small></div><div><strong>3</strong><span>interactive models</span><small>Diffusion, inheritance and growth</small></div></div></header>
    <section id="atlas" className="bio-atlas"><header className="bio-atlas-head"><span className="bio-eyebrow">THE LIVING WORLD / A CONNECTED ATLAS</span><h2>One living world. Many ways to study it.</h2><p>Select a star to explore an idea, its study connections and its applications. The rings suggest approximate study levels; advanced topics are not all unsolved, and every branch contains open research.</p></header><BiologyUniverse /><p className="bio-note">This is a curated atlas. The routes are suggested learning paths, and the dependency links are useful connections rather than a complete account of biology.</p></section>
    <div className="bio-meta"><span>{chapters.length} chapters</span><span>3 interactive models</span><span>4 guided atlas routes</span><span>Math → Physics → Biology</span></div><ChapterNav />

    <section id="life" className="bio-chapter"><Heading number="01" title="Life is organized across scales."><p>A useful explanation identifies what is being explained and at what scale. Knowing a molecule&apos;s structure, a cell&apos;s response and a population&apos;s history answers different questions.</p></Heading><ol className="bio-scale">{levelsOfLife.map(item => <li key={item.name}><span className="bio-scale-power">{item.name}</span><div><strong>{item.example}</strong><p>{item.question}</p></div></li>)}</ol><div className="bio-card-grid"><article><h3>Mechanism</h3><p>How does a process occur? Channels, chemical reactions and feedback can explain a cell&apos;s response.</p></article><article><h3>History</h3><p>How did a feature arise and change? Inheritance, common ancestry and environments constrain the answer.</p></article><article><h3>Evidence</h3><p>What observation would distinguish explanations? Measurement, controls and independent replication make the claim testable.</p></article></div><p>Organisms use energy, regulate internal conditions and participate in lineages that reproduce and evolve. No single checklist resolves every boundary case: viruses, for example, depend on host cells for reproduction. Biology investigates these cases rather than defining them away.</p></section>

    <section id="energy" className="bio-chapter"><Heading number="02" title="Chemistry supplies the parts. Energy constrains the process."><p>Water, carbon chemistry and molecular interactions make cells possible. Biology also requires a continuing account of where energy and matter enter, move and leave.</p></Heading><div className="bio-card-grid"><article><h3>Proteins</h3><p>Amino-acid sequences form molecules with structural, catalytic and signaling roles. Function depends on conformation, dynamics, partners and environment; some regions remain disordered.</p></article><article><h3>Nucleic acids</h3><p>DNA stores inherited sequence information in cellular organisms. RNA has coding, regulatory, structural and catalytic roles.</p></article><article><h3>Carbohydrates and lipids</h3><p>Carbohydrates contribute to energy storage, structure and recognition. Lipids include membrane components, stores of energy and signaling molecules.</p></article></div><h3>ATP couples reactions</h3><p>Enzymes lower activation barriers and change reaction rates; they do not change the equilibrium free-energy difference. Coupling a favorable reaction, such as ATP hydrolysis under cellular conditions, to an unfavorable one can make the combined process proceed.</p><aside className="bio-callout"><strong>Local organization does not suspend thermodynamics.</strong><p>Cells are open systems. They exchange matter and energy with their surroundings, and can maintain internal organization while producing entropy overall. The state of the surroundings belongs in the calculation.</p></aside><Link href="/physics#chance" className="bio-study-link">Revisit energy, chance and heat in Physics →</Link></section>

    <section id="cells" className="bio-chapter"><Heading number="03" title="A cell maintains a boundary and a difference."><p>Membranes separate compartments while allowing regulated exchange. A lipid bilayer, embedded proteins and concentration gradients create different routes for different substances.</p></Heading><p>Passive transport proceeds down an appropriate concentration or electrochemical gradient. Active transport couples movement to an energy source and can maintain a gradient. Osmosis concerns water movement; it should not be confused with every kind of solute diffusion.</p><DiffusionLab /><h3>Compartments change what can happen together</h3><p>Eukaryotic cells use organelles to organize processes. Prokaryotic cells have a different organization, and not every cellular structure is membrane-bound. Cells also use cytoskeletal structures, signaling networks and regulated division to coordinate their activity.</p></section>

    <section id="genes" className="bio-chapter"><Heading number="04" title="Information is copied, expressed and regulated."><p>Separate the sequence stored in a genome from when and where its products are made. A sequence alone does not specify the full state of a cell.</p></Heading><div className="bio-sequence" aria-label="Common gene-expression pathway"><span>DNA</span>→<span>Transcription → RNA</span>→<span>Translation → protein</span></div><p>DNA replication copies DNA; transcription produces RNA from a template; translation uses an RNA message to assemble an amino-acid sequence. This familiar pathway is not a claim that every RNA encodes a protein. Reverse transcription also transfers sequence information from RNA to DNA.</p><p>Regulation acts at multiple stages, including access to DNA, transcription, RNA processing, translation and degradation. Many cell types share most of their genome but express different combinations of genes. Alternative splicing can generate different products from one gene.</p><h3>Inheritance is more than a dominant/recessive table</h3><p>An allele is a sequence variant at a locus. Genotype describes the variants carried; phenotype describes an observed trait. Dominance is a relationship between alleles for a specified phenotype, not a measure of strength, frequency or evolutionary value. Many traits depend on multiple loci and the environment.</p><a className="bio-study-link" href="https://www.genome.gov/genetics-glossary/Central-Dogma">Read the NHGRI introduction to genetic information flow ↗</a></section>

    <section id="evolution" className="bio-chapter"><Heading number="05" title="Variation has consequences across generations."><p>Evolution describes changes in inherited population characteristics across generations. Natural selection is one mechanism; it is not the entire process.</p></Heading><div className="bio-card-grid"><article><h3>Mutation and recombination</h3><p>Mutation changes sequence; recombination rearranges existing variation. Effects depend on context and are not directed toward an organism&apos;s future needs.</p></article><article><h3>Selection and drift</h3><p>Selection involves differences in reproductive success associated with heritable variation. Drift changes frequencies through finite-population sampling.</p></article><article><h3>Gene flow and ancestry</h3><p>Migration and reproduction move alleles between populations. Shared ancestry explains similarities while different histories explain divergence.</p></article></div><InheritanceLab /><p>Fitness refers to reproductive contribution in a specified setting. It does not imply progress toward a universal best organism. A trait can be advantageous in one environment, costly in another, or carried along with another selected trait.</p></section>

    <section id="systems" className="bio-chapter"><Heading number="06" title="Bodies coordinate through signals and feedback."><p>Development builds organized tissues from cells. Physiology studies how those tissues function together, while neuroscience asks how nervous systems sense, act and change with experience.</p></Heading><div className="bio-card-grid"><article><h3>Homeostasis</h3><p>Negative feedback can resist disturbances to temperature, concentration or other regulated quantities. Real biological control has delays, changing targets and limits.</p></article><article><h3>Nervous systems</h3><p>Membrane potentials, action potentials and synapses support signaling. Network behavior depends on cell properties, connections and ongoing activity.</p></article><article><h3>Immune systems</h3><p>Innate defenses and adaptive responses contribute differently to protection. Immune memory involves biological cell populations and molecular recognition.</p></article></div><h3>A neural network is a model, not a miniature brain</h3><p>Artificial neurons use simplified mathematical operations. Biological neurons have spatial structure, biochemical states and multiple timescales. Similar vocabulary can inspire a question, but it does not establish that the two systems learn or represent information in the same way.</p><Link className="bio-study-link" href="/simulations#control">Explore feedback in the simulation lab →</Link></section>

    <section id="ecology" className="bio-chapter"><Heading number="07" title="An organism changes the system it lives in."><p>Ecology connects organisms to one another and to resources, climate and habitat. Energy flows through food webs, while matter cycles through living and nonliving components.</p></Heading><PopulationLab /><p>Predator–prey interactions, competition and cooperation can create feedback at population scales. Simple models isolate a mechanism; field observations determine whether that mechanism is sufficient in a particular setting.</p><Link className="bio-study-link" href="/simulations#emergence">See how local interaction rules produce collective behavior →</Link></section>

    <section id="computing" className="bio-chapter"><Heading number="08" title="A useful prediction still needs a biological test."><p>Computation helps organize measurements, estimate relationships and propose explanations. The experimental design determines which conclusions the data can support.</p></Heading><aside className="bio-callout"><strong>Count independent biological units.</strong><p>One hundred images from one specimen are not one hundred independent specimens. Split data at the level required by the claim—such as donor, organism, site or related sequence family—and distinguish biological replication from repeated measurement.</p></aside><div className="bio-table-wrap" tabIndex={0} role="region" aria-label="Biology and computing"><table><thead><tr><th scope="col">Task</th><th scope="col">Data</th><th scope="col">Computational approach</th><th scope="col">What to check</th></tr></thead><tbody>{bridges.map(b => <tr key={b.task}><th scope="row">{b.task}</th><td>{b.data}</td><td>{b.method}</td><td>{b.check}</td></tr>)}</tbody></table></div><p>AlphaFold&apos;s 2021 study demonstrated major improvements in protein structure prediction on the CASP14 benchmark. That result supports a specific prediction task; it does not mean that sequence alone answers every question about a protein&apos;s function, dynamics or behavior inside a cell.</p><a className="bio-study-link" href="https://www.nature.com/articles/s41586-021-03819-2">Read the original AlphaFold study ↗</a><p>For intervention claims, distinguish correlation from causation and include appropriate controls. Biological and clinical outcomes require their own evidence; success on a computational benchmark is a different kind of result.</p></section>

    <section id="questions" className="bio-chapter"><Heading number="09" title="Keep the unresolved questions visible."><p>A field can have strong explanations for particular mechanisms while still lacking a complete account across scales.</p></Heading><div className="bio-open-grid">{openQuestions.map((q, i) => <article key={q.title}><span className="bio-eyebrow">QUESTION 0{i + 1}</span><h3>{q.title}</h3><p>{q.text}</p></article>)}</div></section>

    <section id="start" className="bio-chapter"><Heading number="10" title="Build an explanation you can test."><p>Use the chapters as a starting path and the atlas to explore connections. Return to Math for the model and Physics for its physical assumptions.</p></Heading><ol className="bio-steps">{learningSteps.map((step, i) => <li key={step.title}><span className="bio-eyebrow">STEP 0{i + 1}</span><strong>{step.title}</strong><p>{step.task}</p></li>)}</ol><h3>Keep studying</h3><div className="bio-resource-grid">{resources.map(r => <article key={r.href}><h4><a href={r.href}>{r.name} ↗</a></h4><p>{r.note}</p></article>)}</div><div className="bio-next-grid"><Link href="/physics"><span className="bio-eyebrow">PREVIOUS FOUNDATION</span><h3>Physics →</h3><p>Revisit energy, transport and feedback.</p></Link><Link href="/#python-fundamentals"><span className="bio-eyebrow">CONTINUE THE LEARNING PATH</span><h3>Python, AI and machine learning →</h3><p>Use computation to explore the systems you have studied.</p></Link></div></section>
    <footer className="bio-footer"><p>Follow the mechanism. Account for history. Test the explanation.</p><a href="#atlas">Back to the biology atlas ↑</a></footer>
  </main>;
}
