/**
 * A physics atlas, plotted as one circle.
 *
 * Distance from the centre suggests a study level, not a strict prerequisite
 * order. The outer bands include both established theory and open research.
 * Each wedge is a branch. `compute` marks the places where this subject and
 * machine learning genuinely touch, which is more often than either field's
 * introductions admit.
 */

export type BranchId =
  | "mechanics" | "waves" | "fluids" | "thermo" | "em" | "optics"
  | "relativity" | "quantum" | "particle" | "matter" | "cosmos" | "methods";

export const branches: { id: BranchId; label: string; short: string }[] = [
  { id: "mechanics", label: "Classical mechanics", short: "Mechanics" },
  { id: "waves", label: "Waves & oscillations", short: "Waves" },
  { id: "fluids", label: "Fluids & continuum", short: "Fluids" },
  { id: "thermo", label: "Thermodynamics & statistical mechanics", short: "Thermal" },
  { id: "em", label: "Electromagnetism", short: "Electromagnetism" },
  { id: "optics", label: "Optics & photonics", short: "Optics" },
  { id: "relativity", label: "Relativity", short: "Relativity" },
  { id: "quantum", label: "Quantum mechanics", short: "Quantum" },
  { id: "particle", label: "Particle & nuclear", short: "Particles" },
  { id: "matter", label: "Condensed matter", short: "Matter" },
  { id: "cosmos", label: "Astrophysics & cosmology", short: "Cosmos" },
  { id: "methods", label: "Methods & computation", short: "Methods" },
];

export const levels = ["Everyday observations", "School foundations", "Core university", "Deeper connections", "Advanced study & frontiers"];

export type Idea = {
  id: string; name: string; branch: BranchId; ring: 0 | 1 | 2 | 3 | 4;
  what: string;
  compute?: string;  // a real link to computation or machine learning
  world?: string;    // where it shows up outside a textbook
  life?: { detail: string; href: `/biology#${string}` };
  needs?: string[];
};

export const ideas: Idea[] = [
  /* ---- Classical mechanics ------------------------------------------------ */
  { id: "position", name: "Position & time", branch: "mechanics", ring: 0, what: "Where something is, and when. Every other quantity in mechanics is built from these two.", world: "Every map, timetable and tracking system." },
  { id: "velocity", name: "Velocity", branch: "mechanics", ring: 0, what: "The rate at which position changes — the first derivative, and the first time calculus earns its keep.", compute: "The same derivative a training loop takes, applied to distance instead of loss.", world: "Speedometers.", needs: ["position"] },
  { id: "acceleration", name: "Acceleration", branch: "mechanics", ring: 1, what: "The rate at which velocity changes. What you actually feel when a car pulls away.", world: "Every phone contains an accelerometer measuring exactly this.", needs: ["velocity"] },
  { id: "newton", name: "Newton's laws", branch: "mechanics", ring: 1, what: "Objects keep doing what they were doing; force equals mass times acceleration; every push has an equal push back.", compute: "F = ma is the update rule a physics engine integrates, step after step.", world: "Bridges, vehicles, and roughly everything built before 1900.", needs: ["acceleration"] },
  { id: "momentum", name: "Momentum", branch: "mechanics", ring: 1, what: "Mass times velocity. In an isolated system the total never changes, whatever happens inside it.", compute: "The optimiser term borrowed the name for a reason: both accumulate a direction and resist sudden change.", world: "Collisions, rocketry, recoil.", needs: ["newton"] },
  { id: "energy", name: "Energy", branch: "mechanics", ring: 1, what: "A number that stays the same as a system rearranges itself. Not a substance — a bookkeeping quantity that happens never to go missing.", compute: "Energy conservation is the test that exposes a bad integrator, as the orbit panel on the simulations page shows.", world: "Every bill you pay for it.", needs: ["newton"] },
  { id: "work-power", name: "Work & power", branch: "mechanics", ring: 1, what: "Work is force applied along a distance; power is how quickly you do it.", world: "Engine ratings, and the wattage of the GPU training your model.", needs: ["energy"] },
  { id: "rotation", name: "Rotation & torque", branch: "mechanics", ring: 2, what: "The same laws again, for things that spin: torque, moment of inertia, angular momentum.", compute: "The pole in a CartPole environment is this and nothing else.", world: "Wheels, gyroscopes, figure skaters pulling their arms in.", needs: ["momentum"] },
  { id: "gravitation", name: "Universal gravitation", branch: "mechanics", ring: 2, what: "Every mass attracts every other, falling off as the square of the distance.", compute: "The force law in the orbit simulation, and the classic n-body benchmark.", world: "Tides, orbits, and the reason you are on the floor.", needs: ["newton"] },
  { id: "oscillator", name: "The harmonic oscillator", branch: "mechanics", ring: 2, what: "A restoring force proportional to displacement. The single most reused model in all of physics.", compute: "Near any minimum, a loss surface looks like one — which is what a second-order optimiser exploits.", world: "Springs, pendulums, atoms in a crystal, LC circuits.", needs: ["newton", "energy"] },
  { id: "lagrangian", name: "Lagrangian mechanics", branch: "mechanics", ring: 3, what: "Reformulate motion as the path that makes the action stationary. Same predictions, far better with constraints.", compute: "Lagrangian and Hamiltonian neural networks build this structure into the architecture rather than hoping it is learned.", needs: ["energy", "variational"] },
  { id: "hamiltonian", name: "Hamiltonian mechanics", branch: "mechanics", ring: 3, what: "Describe a system by position and momentum together, evolving in phase space.", compute: "Hamiltonian Monte Carlo samples probability distributions by pretending they are a physical system and rolling a ball across them.", needs: ["lagrangian"] },
  { id: "noether", name: "Noether's theorem", branch: "mechanics", ring: 3, what: "Every continuous symmetry of the action gives a conserved quantity. Time symmetry gives energy; space symmetry gives momentum.", compute: "The formal reason equivariant networks work: build in the symmetry and you get the invariance for free.", needs: ["lagrangian", "symmetry-p"] },
  { id: "chaos", name: "Deterministic chaos", branch: "mechanics", ring: 3, what: "Fully determined equations whose outcomes are unpredictable, because tiny differences grow exponentially.", compute: "The hard ceiling on long-horizon simulation and weather prediction — no model resolution removes it.", world: "The double pendulum, the weather, the three-body problem.", needs: ["oscillator", "nonlinear"] },
  { id: "rigid-body", name: "Rigid-body dynamics", branch: "mechanics", ring: 2, what: "Bodies that do not deform, colliding and pivoting and resting on each other.", compute: "What MuJoCo, Bullet and every game engine actually solve.", needs: ["rotation"] },
  { id: "three-body", name: "The n-body problem", branch: "mechanics", ring: 4, what: "Three or more gravitating bodies admit no general closed-form solution. You integrate, and you accept error.", compute: "The benchmark that made symplectic integrators matter.", needs: ["gravitation", "chaos"] },

  /* ---- Waves & oscillations ----------------------------------------------- */
  { id: "wave", name: "What a wave is", branch: "waves", ring: 1, what: "A disturbance that carries energy through a medium without carrying the medium with it.", world: "Sound, ripples, light, earthquakes.", needs: ["oscillator"] },
  { id: "frequency", name: "Frequency & wavelength", branch: "waves", ring: 1, what: "How often it repeats in time, and how far it repeats in space. Their product is the speed.", compute: "Sample rate, Nyquist limits, and why audio models care about both.", world: "Radio dials, musical pitch, colour.", needs: ["wave"] },
  { id: "superposition", name: "Superposition", branch: "waves", ring: 2, what: "Waves pass through each other and simply add. Nothing is lost in the crossing.", compute: "Linearity, which is exactly why a linear layer cannot do everything.", world: "Every conversation in a crowded room reaching you intact.", needs: ["wave"] },
  { id: "interference", name: "Interference", branch: "waves", ring: 2, what: "Added waves can reinforce or cancel, producing patterns from nothing but timing.", world: "Noise-cancelling headphones, oil-film colours, the double slit.", needs: ["superposition"] },
  { id: "resonance", name: "Resonance", branch: "waves", ring: 2, what: "Drive a system near its natural frequency and the response grows enormously.", compute: "The instability in the timestep panel is a numerical version of the same thing.", world: "Wine glasses, bridges, MRI, tuning a radio.", needs: ["oscillator", "frequency"] },
  { id: "damping", name: "Damping", branch: "waves", ring: 2, what: "Energy leaking out of an oscillation, and the three regimes — under, critical, over — that follow.", compute: "Exactly the derivative term in a PID controller, and the momentum decay in an optimiser.", world: "Car suspension, door closers.", needs: ["oscillator"] },
  { id: "standing", name: "Standing waves & modes", branch: "waves", ring: 2, what: "Confine a wave and only certain frequencies survive. The rest cancel themselves out.", compute: "Eigenvalue problems: the modes are eigenvectors of the wave operator.", world: "Musical instruments, laser cavities, electron orbitals.", needs: ["interference"] },
  { id: "doppler", name: "Doppler effect", branch: "waves", ring: 2, what: "Motion shifts observed frequency: approaching is higher, receding is lower.", world: "Sirens, radar guns, and how we know the universe is expanding.", needs: ["frequency"] },
  { id: "fourier-p", name: "Fourier decomposition", branch: "waves", ring: 3, what: "Any signal is a sum of pure sinusoids. Choose whichever description makes the problem easy.", compute: "FFT convolution, spectrograms, positional encodings, and the spectral bias of neural networks.", world: "Audio compression, image formats, every codec.", needs: ["superposition"] },
  { id: "dispersion", name: "Dispersion", branch: "waves", ring: 3, what: "When speed depends on frequency, a pulse made of many frequencies spreads out as it travels.", world: "Prisms, rainbows, and why long fibre-optic runs need repeaters.", needs: ["frequency"] },
  { id: "nonlinear", name: "Nonlinear waves", branch: "waves", ring: 4, what: "When superposition fails, waves interact — producing shocks, solitons and turbulence.", needs: ["superposition"] },
  { id: "acoustics", name: "Acoustics", branch: "waves", ring: 2, what: "How sound is produced, propagated, absorbed and heard.", compute: "Speech recognition and synthesis both start with a physical model of this.", world: "Concert halls, ultrasound, sonar.", needs: ["wave"] },

  /* ---- Fluids & continuum -------------------------------------------------- */
  { id: "pressure", name: "Pressure", branch: "fluids", ring: 1, what: "Force spread over an area. In a still fluid it pushes equally in all directions.", world: "Weather maps, tyres, diving, blood.", needs: ["newton"] },
  { id: "buoyancy", name: "Buoyancy", branch: "fluids", ring: 1, what: "A submerged object is pushed up by the weight of the fluid it displaced.", world: "Ships, balloons, and why ice floats.", needs: ["pressure"] },
  { id: "viscosity", name: "Viscosity", branch: "fluids", ring: 2, what: "A fluid's internal friction — its reluctance to be sheared.", compute: "A parameter that has to be guessed in most simulations, and rarely measured.", world: "Honey, engine oil, lava.", needs: ["pressure"] },
  { id: "bernoulli", name: "Bernoulli's principle", branch: "fluids", ring: 2, what: "Along a streamline, faster flow comes with lower pressure — energy conservation in disguise.", world: "Wings, carburettors, spray bottles.", needs: ["energy", "pressure"] },
  { id: "navier-stokes", name: "Navier–Stokes equations", branch: "fluids", ring: 3, what: "The equations of fluid motion. Easy to write, unreasonably hard to solve.", compute: "The headline target for neural operators and physics-informed networks.", world: "Weather, aerodynamics, blood flow, climate.", needs: ["viscosity", "pde-p"] },
  { id: "reynolds", name: "Reynolds number", branch: "fluids", ring: 3, what: "One dimensionless ratio deciding whether flow is smooth or chaotic.", compute: "A reminder that the right non-dimensional grouping can replace a dozen parameters.", world: "Why a model aircraft does not fly like the real one.", needs: ["viscosity"] },
  { id: "turbulence", name: "Turbulence", branch: "fluids", ring: 4, what: "Chaotic flow across an enormous range of scales. Widely called the last great unsolved problem of classical physics.", compute: "Resolving every scale is beyond any computer, so every simulation models what it cannot resolve — increasingly with learned closures.", world: "Aircraft design, climate models, mixing.", needs: ["navier-stokes", "chaos"] },
  { id: "elasticity", name: "Elasticity", branch: "fluids", ring: 2, what: "How solids deform under load and spring back.", compute: "Soft-body and cloth simulation; deformable grasping.", world: "Buildings, springs, biological tissue.", needs: ["newton"] },
  { id: "surface-tension", name: "Surface tension", branch: "fluids", ring: 2, what: "A liquid surface behaving like a stretched skin, because molecules prefer company.", world: "Droplets, insects on water, capillary action.", needs: ["pressure"] },

  /* ---- Thermodynamics & statistical mechanics ------------------------------ */
  { id: "temperature", name: "Temperature", branch: "thermo", ring: 0, what: "Not how much energy there is, but how it is shared. Two things at the same temperature exchange no net heat.", world: "Weather, cooking, fever." },
  { id: "heat", name: "Heat & internal energy", branch: "thermo", ring: 1, what: "Energy transferred because of a temperature difference, and the energy already stored inside.", compute: "Why data centres are built around cooling before compute.", world: "Kettles, engines, insulation.", needs: ["temperature", "energy"] },
  { id: "first-law", name: "First law", branch: "thermo", ring: 2, what: "Energy is conserved once heat is counted as a form of it.", world: "The death of the perpetual motion machine.", needs: ["heat"] },
  { id: "entropy", name: "Entropy", branch: "thermo", ring: 2, what: "A measure of how many microscopic arrangements match what you can actually see.", compute: "The identical quantity Shannon arrived at independently for information — cross-entropy loss is this idea.", world: "Why heat flows one way and eggs do not unscramble.", needs: ["first-law", "probability-p"] },
  { id: "second-law", name: "Second law", branch: "thermo", ring: 2, what: "The total entropy of an isolated macroscopic system does not decrease in a spontaneous process. A subsystem can become more ordered by exchanging energy and matter with its surroundings.", world: "Efficiency limits on heat engines.", life: { detail: "Cells maintain organization while exchanging energy and matter; their surroundings must be included in the entropy account.", href: "/biology#energy" }, needs: ["entropy"] },
  { id: "boltzmann", name: "Boltzmann distribution", branch: "thermo", ring: 3, what: "At equilibrium, the chance of a state falls exponentially with its energy over temperature.", compute: "Softmax is a Boltzmann distribution with the logits as negative energies. Temperature sampling is literally temperature.", needs: ["entropy", "probability-p"] },
  { id: "partition", name: "Partition function", branch: "thermo", ring: 3, what: "Sum over all states of their Boltzmann weights. Differentiate it and every thermodynamic quantity falls out.", compute: "The normalising constant in an energy-based model, and the reason they are hard to train.", needs: ["boltzmann"] },
  { id: "free-energy", name: "Free energy", branch: "thermo", ring: 3, what: "Helmholtz free energy F = U − TS is minimized at equilibrium at fixed temperature and volume. At fixed temperature and pressure, the corresponding potential is Gibbs free energy G = H − TS, subject to the system's constraints.", compute: "Variational objectives in probabilistic models use a related energy–entropy balance; their terms need not be physical energies.", life: { detail: "Reaction free-energy changes explain how ATP hydrolysis can be coupled to cellular work. Concentrations and conditions matter.", href: "/biology#energy" }, needs: ["partition"] },
  { id: "ising", name: "The Ising model", branch: "thermo", ring: 3, what: "Spins on a lattice preferring to agree with their neighbours. The simplest model with a real phase transition.", compute: "Hopfield networks and Boltzmann machines are this model with the couplings learned.", needs: ["boltzmann"] },
  { id: "phase-transition", name: "Phase transitions", branch: "thermo", ring: 3, what: "A tiny change in a parameter producing a qualitative change in the whole system.", compute: "Proposed as the frame for emergent capabilities and grokking, though whether these are genuine transitions is contested.", world: "Boiling, freezing, magnetisation.", needs: ["ising"] },
  { id: "renormalization", name: "Renormalisation group", branch: "thermo", ring: 4, what: "Systematically coarse-grain a system and watch which details stop mattering.", compute: "An appealing analogy for what depth does in a network. Suggestive rather than established.", needs: ["phase-transition"] },
  { id: "langevin", name: "Langevin dynamics", branch: "thermo", ring: 4, what: "Motion driven by a force plus random thermal kicks.", compute: "The sampler underneath score-based diffusion models, and one lens on the noise in SGD.", needs: ["boltzmann", "stochastic-p"] },
  { id: "fluctuation", name: "Fluctuation–dissipation", branch: "thermo", ring: 4, what: "How strongly a system responds to a push is fixed by how much it jiggles on its own.", needs: ["langevin"] },
  { id: "noneq", name: "Non-equilibrium thermodynamics", branch: "thermo", ring: 4, what: "Systems with flows, gradients or time-dependent driving that keep them away from equilibrium.", compute: "Non-equilibrium processes inspired the original formulation of diffusion generative models.", life: { detail: "Metabolism and transport sustain gradients. A living cell exchanges energy and materials instead of relaxing to equilibrium.", href: "/biology#energy" }, needs: ["second-law", "langevin"] },
  { id: "maxwell-demon", name: "Information & thermodynamics", branch: "thermo", ring: 4, what: "Erasing a bit costs a minimum amount of energy. Information is physical.", compute: "Landauer's limit is a hard floor under the energy cost of computation.", needs: ["entropy", "second-law"] },

  /* ---- Electromagnetism ---------------------------------------------------- */
  { id: "charge", name: "Electric charge", branch: "em", ring: 1, what: "A property with two signs; like repels like. Conserved absolutely.", world: "Static shocks, lightning, every chemical bond." },
  { id: "field", name: "Fields", branch: "em", ring: 1, what: "Instead of action at a distance, a quantity defined everywhere that tells a charge what to do locally.", compute: "The mental model behind every continuous representation, including neural fields.", needs: ["charge"] },
  { id: "coulomb", name: "Coulomb's law", branch: "em", ring: 1, what: "Force between charges falls off as the square of distance — the same shape as gravity, vastly stronger.", needs: ["charge", "gravitation"] },
  { id: "current", name: "Current & circuits", branch: "em", ring: 1, what: "Charge in motion, and the rules for routing it through components.", world: "Literally every electronic device.", needs: ["charge"] },
  { id: "magnetism", name: "Magnetism", branch: "em", ring: 2, what: "Moving charges create fields that push other moving charges. Relativity in everyday disguise.", world: "Motors, hard drives, compasses.", needs: ["current"] },
  { id: "induction", name: "Electromagnetic induction", branch: "em", ring: 2, what: "A changing magnetic field drives a current. The basis of generating electricity at all.", world: "Power stations, transformers, wireless charging.", needs: ["magnetism"] },
  { id: "maxwell", name: "Maxwell's equations", branch: "em", ring: 3, what: "Four equations unifying electricity, magnetism and light — and predicting the speed of light from measurements that had nothing to do with it.", compute: "Solved numerically in every antenna and chip-layout tool.", needs: ["induction", "field"] },
  { id: "em-wave", name: "Electromagnetic waves", branch: "em", ring: 3, what: "Self-sustaining ripples of field, travelling at c, from radio to gamma.", world: "All wireless communication, all of astronomy.", needs: ["maxwell", "wave"] },
  { id: "circuits-ac", name: "AC circuits & impedance", branch: "em", ring: 2, what: "Driving circuits with oscillating sources, where complex numbers make the algebra tractable.", needs: ["current", "complex-p"] },
  { id: "semiconductor", name: "Semiconductors", branch: "em", ring: 3, what: "Materials whose conductivity can be controlled, which is the entire reason transistors exist.", compute: "Every GPU that has ever trained a model.", needs: ["current", "band"] },
  { id: "plasma", name: "Plasma physics", branch: "em", ring: 4, what: "Ionised gas, where electromagnetism and fluid dynamics are inseparable.", compute: "Fusion reactor control is now a live reinforcement-learning application.", world: "Stars, lightning, fusion reactors, neon signs.", needs: ["maxwell", "navier-stokes"] },

  /* ---- Optics -------------------------------------------------------------- */
  { id: "reflection", name: "Reflection & refraction", branch: "optics", ring: 1, what: "Light bounces predictably, and bends when the speed of propagation changes.", compute: "Ray tracing, and the rendering inside every photorealistic simulator.", world: "Mirrors, lenses, why a straw looks broken in water.", needs: ["wave"] },
  { id: "lens", name: "Lenses & imaging", branch: "optics", ring: 2, what: "Curved surfaces bending rays to a focus, and the geometry of the image that results.", compute: "The camera model every vision system assumes, usually without checking.", world: "Eyes, cameras, telescopes, microscopes.", needs: ["reflection"] },
  { id: "diffraction", name: "Diffraction", branch: "optics", ring: 2, what: "Light spreading around edges and through apertures, because it is a wave.", world: "The resolution limit of every optical instrument.", needs: ["interference"] },
  { id: "polarization", name: "Polarisation", branch: "optics", ring: 2, what: "The orientation of a wave's oscillation, which can be filtered.", world: "Sunglasses, LCD screens, stress analysis.", needs: ["em-wave"] },
  { id: "spectroscopy", name: "Spectroscopy", branch: "optics", ring: 3, what: "Reading what something is made of from the light it emits or absorbs.", compute: "Large-scale automated classification of spectra is now routine machine learning.", world: "Astronomy, chemistry, medical diagnostics.", needs: ["quantum-atom"] },
  { id: "laser", name: "Lasers", branch: "optics", ring: 3, what: "Stimulated emission producing light that is coherent in phase, direction and colour.", world: "Fibre networks, surgery, manufacturing, LIDAR.", needs: ["quantum-atom"] },
  { id: "nonlinear-optics", name: "Nonlinear optics", branch: "optics", ring: 4, what: "At high intensity a material's response stops being proportional, and light can change its own colour.", needs: ["laser", "nonlinear"] },
  { id: "photonics", name: "Photonic computing", branch: "optics", ring: 4, what: "Performing computation with light rather than electrons.", compute: "Optical matrix multiplication is an active line of attack on the energy cost of inference.", needs: ["laser", "semiconductor"] },

  /* ---- Relativity ----------------------------------------------------------- */
  { id: "frames", name: "Reference frames", branch: "relativity", ring: 1, what: "Motion is only ever relative to something else. There is no privileged place to stand.", needs: ["velocity"] },
  { id: "light-speed", name: "The speed of light", branch: "relativity", ring: 2, what: "Measured the same by every observer however they move. Accepting this forces everything else.", needs: ["frames", "em-wave"] },
  { id: "special-rel", name: "Special relativity", branch: "relativity", ring: 3, what: "Time dilates, lengths contract, and simultaneity depends on who is asking.", world: "GPS satellites correct for this or drift kilometres per day.", needs: ["light-speed"] },
  { id: "spacetime", name: "Spacetime", branch: "relativity", ring: 3, what: "Space and time as one four-dimensional geometry rather than a stage and a clock.", compute: "Minkowski geometry; and hyperbolic embeddings borrow the non-Euclidean machinery.", needs: ["special-rel"] },
  { id: "mass-energy", name: "E = mc²", branch: "relativity", ring: 3, what: "Mass is a form of energy. A very small amount of it is an enormous amount of energy.", world: "Nuclear power, the Sun, PET scanners.", needs: ["special-rel"] },
  { id: "general-rel", name: "General relativity", branch: "relativity", ring: 4, what: "Gravity is not a force but the curvature of spacetime by energy and momentum.", compute: "Numerical relativity is among the most demanding simulation problems there is.", world: "Black holes, gravitational lensing, GPS.", needs: ["spacetime", "curvature-p"] },
  { id: "grav-waves", name: "Gravitational waves", branch: "relativity", ring: 4, what: "Ripples in spacetime itself, detected in 2015 a century after being predicted.", compute: "Detection is a signal-processing problem where machine learning now assists the search.", needs: ["general-rel"] },

  /* ---- Quantum mechanics ---------------------------------------------------- */
  { id: "quantization", name: "Quantisation", branch: "quantum", ring: 2, what: "Some quantities come only in discrete amounts. Energy is not always a dial.", world: "Why atoms are stable and why neon glows orange.", needs: ["energy"] },
  { id: "photon", name: "Photons", branch: "quantum", ring: 2, what: "Light arrives in indivisible packets whose energy is set by frequency.", world: "Solar cells, digital cameras, photosynthesis.", needs: ["quantization", "em-wave"] },
  { id: "wave-particle", name: "Wave–particle duality", branch: "quantum", ring: 2, what: "Quantum objects show wave behaviour or particle behaviour depending on what you ask.", world: "Electron microscopy relies on electrons having a wavelength.", needs: ["photon", "interference"] },
  { id: "wavefunction", name: "The wavefunction", branch: "quantum", ring: 3, what: "A complex-valued function whose squared magnitude gives probabilities.", compute: "Its dimension grows exponentially with particle count — the reason quantum simulation is hard.", needs: ["wave-particle", "complex-p"] },
  { id: "schrodinger", name: "Schrödinger equation", branch: "quantum", ring: 3, what: "How a wavefunction evolves. Deterministic; it is measurement that introduces chance.", compute: "Neural network wavefunction ansätze are a serious line of work in quantum chemistry.", needs: ["wavefunction"] },
  { id: "uncertainty", name: "Uncertainty principle", branch: "quantum", ring: 3, what: "Position and momentum cannot both be sharp. Not a measurement limitation — a property of the objects.", needs: ["wavefunction"] },
  { id: "superposition-q", name: "Quantum superposition", branch: "quantum", ring: 3, what: "A system can be in a combination of states until it interacts with something.", needs: ["wavefunction"] },
  { id: "entanglement", name: "Entanglement", branch: "quantum", ring: 4, what: "Correlations between parts of a system that no description of the parts alone can reproduce.", compute: "The resource quantum computing spends, and what tensor networks are built to track.", needs: ["superposition-q"] },
  { id: "quantum-atom", name: "Atomic structure", branch: "quantum", ring: 3, what: "Electrons occupy discrete orbitals; the periodic table is a consequence rather than a catalogue.", world: "All of chemistry.", needs: ["schrodinger"] },
  { id: "spin", name: "Spin", branch: "quantum", ring: 3, what: "An intrinsic angular momentum with no classical analogue, and the origin of magnetism.", world: "MRI scans every spin in your body.", needs: ["quantization"] },
  { id: "measurement", name: "The measurement problem", branch: "quantum", ring: 4, what: "What counts as a measurement, and why one outcome, remain genuinely unsettled.", needs: ["superposition-q"] },
  { id: "qft", name: "Quantum field theory", branch: "quantum", ring: 4, what: "Particles as excitations of underlying fields. The framework behind the Standard Model.", compute: "Lattice calculations are among the largest supercomputing workloads in science.", needs: ["schrodinger", "special-rel"] },
  { id: "quantum-computing", name: "Quantum computing", branch: "quantum", ring: 4, what: "Computation using superposition and entanglement, with a narrow set of genuine advantages.", compute: "Error correction is the bottleneck; claims of broad speedup remain far ahead of hardware.", needs: ["entanglement"] },
  { id: "decoherence", name: "Decoherence", branch: "quantum", ring: 4, what: "Interaction with an environment destroying superposition, which is why the everyday world looks classical.", needs: ["entanglement"] },

  /* ---- Particle & nuclear ---------------------------------------------------- */
  { id: "atom", name: "The atom", branch: "particle", ring: 1, what: "A dense nucleus of protons and neutrons with electrons around it.", world: "Everything you have ever touched.", needs: ["charge"] },
  { id: "isotope", name: "Isotopes & radioactivity", branch: "particle", ring: 2, what: "Nuclei with extra neutrons, some of which decay at fixed statistical rates.", world: "Carbon dating, medical tracers, smoke alarms.", needs: ["atom"] },
  { id: "fission-fusion", name: "Fission & fusion", branch: "particle", ring: 3, what: "Splitting heavy nuclei or joining light ones, both releasing binding energy.", world: "Reactors, the Sun, and the ongoing attempt to build one here.", needs: ["isotope", "mass-energy"] },
  { id: "standard-model", name: "The Standard Model", branch: "particle", ring: 4, what: "Our best inventory of fundamental particles and three of the four forces. Extraordinarily accurate and visibly incomplete.", needs: ["qft"] },
  { id: "higgs", name: "The Higgs mechanism", branch: "particle", ring: 4, what: "How fundamental particles acquire mass through interaction with a field.", compute: "Its discovery leaned on machine-learned classifiers separating signal from background.", needs: ["standard-model"] },
  { id: "neutrino", name: "Neutrinos", branch: "particle", ring: 4, what: "Barely interacting particles that oscillate between flavours — which requires them to have mass the Standard Model did not give them.", needs: ["standard-model"] },
  { id: "beyond-sm", name: "Beyond the Standard Model", branch: "particle", ring: 4, what: "It omits gravity, dark matter, and the matter–antimatter imbalance. Everyone knows it is not the end.", needs: ["standard-model"] },

  /* ---- Condensed matter ------------------------------------------------------ */
  { id: "crystal", name: "Crystal structure", branch: "matter", ring: 2, what: "Atoms arranged in a repeating lattice, whose symmetry dictates the material's properties.", compute: "Graph neural networks predicting material properties from structure is a mature application.", world: "Metals, salt, silicon, snowflakes.", needs: ["atom", "symmetry-p"] },
  { id: "band", name: "Band structure", branch: "matter", ring: 3, what: "In a periodic lattice, allowed electron energies form bands with gaps between them. Conductor, insulator or semiconductor follows from where the gap sits.", needs: ["crystal", "quantum-atom"] },
  { id: "phonon", name: "Phonons", branch: "matter", ring: 3, what: "Quantised lattice vibrations, treated as particles because it makes the arithmetic work.", needs: ["crystal", "quantization"] },
  { id: "superconduct", name: "Superconductivity", branch: "matter", ring: 4, what: "Zero electrical resistance below a critical temperature. Low-temperature cases are understood; high-temperature ones are not.", world: "MRI magnets, maglev, and fusion confinement.", needs: ["band", "phonon"] },
  { id: "magnetism-matter", name: "Magnetic order", branch: "matter", ring: 3, what: "Spins aligning collectively to make a material magnetic, and losing it above a critical temperature.", compute: "The Ising model was invented for this, and ended up describing associative memory.", needs: ["spin", "ising"] },
  { id: "soft-matter", name: "Soft matter", branch: "matter", ring: 3, what: "Polymers, gels, colloids and liquid crystals — materials easily deformed by everyday forces.", world: "Plastics, paint, displays, biological tissue.", needs: ["elasticity"] },
  { id: "topological", name: "Topological phases", branch: "matter", ring: 4, what: "States of matter classified by global invariants rather than local order, making them remarkably robust.", compute: "One proposed route to error-resistant quantum computing.", needs: ["band", "topology-p"] },
  { id: "spin-glass", name: "Spin glasses", branch: "matter", ring: 4, what: "Disordered magnets with conflicting interactions and an enormous landscape of near-degenerate minima.", compute: "The closest physical analogy anyone has for a deep network's loss landscape, and a genuine source of theory.", needs: ["ising", "magnetism-matter"] },

  /* ---- Astrophysics & cosmology ---------------------------------------------- */
  { id: "orbits", name: "Orbits", branch: "cosmos", ring: 1, what: "Falling continuously and missing, which is all an orbit is.", compute: "The test problem in the integrator panel.", world: "Satellites, GPS, the Moon.", needs: ["gravitation"] },
  { id: "stars", name: "Stellar structure", branch: "cosmos", ring: 3, what: "A star is a balance between gravity pulling in and fusion pressure pushing out, held for billions of years.", needs: ["fission-fusion", "pressure"] },
  { id: "stellar-death", name: "Stellar evolution & remnants", branch: "cosmos", ring: 3, what: "What a star becomes when the fuel runs out: white dwarf, neutron star or black hole.", world: "Every element heavier than iron was made in one of these events.", needs: ["stars"] },
  { id: "black-hole", name: "Black holes", branch: "cosmos", ring: 4, what: "Regions where spacetime curvature prevents escape, characterised by remarkably few numbers.", compute: "The first image required assembling a telescope the size of Earth from timing data.", needs: ["general-rel", "stellar-death"] },
  { id: "expansion", name: "The expanding universe", branch: "cosmos", ring: 3, what: "Distant galaxies recede faster the further away they are. Space itself is stretching.", needs: ["doppler", "general-rel"] },
  { id: "cmb", name: "Cosmic microwave background", branch: "cosmos", ring: 4, what: "Light released when the universe first became transparent, now the most precisely measured signal in cosmology.", compute: "Its tiny anisotropies are extracted by large-scale statistical inference.", needs: ["expansion", "photon"] },
  { id: "dark-matter", name: "Dark matter", branch: "cosmos", ring: 4, what: "Something with mass that we see only gravitationally. Decades of searching have not identified it.", needs: ["general-rel", "expansion"] },
  { id: "dark-energy", name: "Dark energy", branch: "cosmos", ring: 4, what: "Whatever is accelerating the expansion. The name is a label for our ignorance.", needs: ["expansion"] },
  { id: "nucleosynthesis", name: "Nucleosynthesis", branch: "cosmos", ring: 4, what: "Where the elements came from — the first minutes, stellar cores, and violent stellar deaths.", needs: ["fission-fusion", "stellar-death"] },

  /* ---- Methods & computation --------------------------------------------------- */
  { id: "units", name: "Units & dimensional analysis", branch: "methods", ring: 0, what: "Checking that both sides of an equation describe the same kind of thing. Catches more errors than any other habit.", compute: "Shape checking in array code is the same discipline wearing different notation." },
  { id: "measurement-err", name: "Measurement & uncertainty", branch: "methods", ring: 1, what: "No measurement is a number; it is a number with an error bar, and the bar is part of the result.", compute: "The error bars missing from most benchmark tables.", needs: ["units"] },
  { id: "estimation", name: "Order-of-magnitude estimation", branch: "methods", ring: 1, what: "Getting within a factor of ten before doing anything precise.", compute: "The fastest way to know whether a training run is even affordable.", needs: ["units"] },
  { id: "probability-p", name: "Probability in physics", branch: "methods", ring: 2, what: "Sometimes ignorance about a system, sometimes irreducible. Statistical mechanics and quantum mechanics mean different things by it.", needs: ["measurement-err"] },
  { id: "symmetry-p", name: "Symmetry arguments", branch: "methods", ring: 2, what: "Work out what cannot change, and you have often solved most of the problem without calculating.", compute: "The design principle behind equivariant and geometric deep learning.", needs: ["units"] },
  { id: "complex-p", name: "Complex amplitudes", branch: "methods", ring: 2, what: "Using complex numbers to carry magnitude and phase together, which turns wave algebra into arithmetic.", needs: ["probability-p"] },
  { id: "variational", name: "Variational principles", branch: "methods", ring: 3, what: "Nature picks the path that makes some quantity stationary. Much of physics restates as an optimisation.", compute: "The same shape as minimising a loss — and the origin of the word variational in machine learning.", needs: ["symmetry-p"] },
  { id: "pde-p", name: "Field equations & PDEs", branch: "methods", ring: 3, what: "Most of physics is written as partial differential equations relating rates of change across space and time.", compute: "Physics-informed networks and neural operators aim at solving these faster than classical solvers.", needs: ["variational"] },
  { id: "numerical-p", name: "Numerical simulation", branch: "methods", ring: 3, what: "Discretise, step, and watch the error. Most modern physics is done this way.", compute: "Everything on the simulations page.", needs: ["pde-p"] },
  { id: "monte-carlo-p", name: "Monte Carlo methods", branch: "methods", ring: 3, what: "Sample randomly to evaluate what cannot be integrated. Invented for neutron transport.", compute: "The same algorithm family as MCMC in Bayesian inference.", needs: ["probability-p", "numerical-p"] },
  { id: "stochastic-p", name: "Stochastic processes", branch: "methods", ring: 4, what: "Systems evolving with randomness built into the dynamics rather than added at the end.", compute: "Diffusion models are stochastic differential equations run backwards.", needs: ["monte-carlo-p"] },
  { id: "curvature-p", name: "Differential geometry", branch: "methods", ring: 4, what: "Calculus on curved spaces — the language general relativity is written in.", needs: ["pde-p"] },
  { id: "topology-p", name: "Topological invariants", branch: "methods", ring: 4, what: "Quantities that survive continuous deformation, and therefore cannot be destroyed by small perturbations.", needs: ["curvature-p"] },
  { id: "ml-physics", name: "Machine learning for physics", branch: "methods", ring: 4, what: "Learned surrogates, emulators and closures where the exact calculation is too slow to run.", compute: "The most honest framing: a fast approximation to a known equation, valid over the distribution it was trained on and no further.", needs: ["numerical-p", "stochastic-p"] },

  /* ---- Entry points: the physics you already know without being taught ---- */
  { id: "sound", name: "Sound", branch: "waves", ring: 0, what: "Air pushed into compressions and rarefactions that your ear decodes. The first wave anybody meets.", world: "Speech, music, a door slamming." },
  { id: "flow", name: "Flow", branch: "fluids", ring: 0, what: "Stuff that cannot hold a shape, moving from where there is more to where there is less.", world: "Taps, rivers, wind, traffic." },
  { id: "attraction", name: "Push without touching", branch: "em", ring: 0, what: "Magnets and static do something gravity also does: act across a gap. Explaining that gap is what fields are for.", world: "Fridge magnets, a balloon on your hair." },
  { id: "light-shadow", name: "Light & shadow", branch: "optics", ring: 0, what: "Light travels in straight lines until something stops or bends it. Almost all of optics is that sentence made precise.", world: "Sundials, silhouettes, eclipses." },
  { id: "relative-motion", name: "Relative motion", branch: "relativity", ring: 0, what: "On a smooth train you cannot tell you are moving. That observation, taken seriously, produces relativity.", world: "Feeling the other train move when yours does." },
  { id: "states-matter", name: "Solid, liquid, gas", branch: "matter", ring: 0, what: "The same atoms, arranged three ways, behaving completely differently.", world: "Ice, water, steam — one substance, three materials." },
  { id: "stuff", name: "Everything is made of pieces", branch: "particle", ring: 0, what: "Matter is not continuous. Divide far enough and you reach a small number of repeating kinds.", world: "The idea that took from Democritus to Einstein to confirm." },
  { id: "night-sky", name: "The night sky", branch: "cosmos", ring: 0, what: "Points of light at wildly different distances, most of them older than the light is young.", world: "Navigation, calendars, and the oldest science there is." },
  { id: "hot-cold", name: "Hot and cold", branch: "thermo", ring: 0, what: "Things left alone end up the same temperature. Never the other way round.", world: "A cup of tea, every time.", needs: ["temperature"] },
  { id: "friction", name: "Friction", branch: "mechanics", ring: 1, what: "The force that opposes sliding, and the reason nothing coasts forever.", compute: "The parameter most often guessed in a simulator and most often wrong on hardware.", world: "Walking, braking, striking a match.", needs: ["newton"] },
  { id: "pendulum", name: "The pendulum", branch: "mechanics", ring: 1, what: "A weight on a string, whose period barely depends on how far you pull it — until you pull it a long way.", compute: "Two of them linked is the standard demonstration of chaos.", world: "Clocks, for three hundred years.", needs: ["oscillator"] },
  { id: "colour", name: "Colour", branch: "optics", ring: 1, what: "Wavelength, as interpreted by three kinds of cell in your eye. The physics and the perception are not the same thing.", compute: "Why colour spaces exist, and why RGB is a convention rather than a measurement.", world: "Screens, paint, rainbows.", needs: ["light-shadow", "frequency"] },
  { id: "electricity-home", name: "Voltage & power", branch: "em", ring: 1, what: "Voltage is the push, current is the flow, and their product is the rate of energy delivery.", compute: "The number on a GPU's spec sheet that decides what your cluster costs to run.", world: "Every plug socket.", needs: ["current"] },

  /* ---- Physical mechanisms that lead into biology ------------------------ */
  { id: "brownian", name: "Brownian motion", branch: "thermo", ring: 2, what: "The irregular motion of a suspended particle caused by thermal collisions with the surrounding fluid.", compute: "Random walks and stochastic models describe its statistics.", world: "Particles jittering under a microscope.", life: { detail: "Thermal motion matters at cellular scales, where particles continually encounter one another and their surroundings.", href: "/biology#cells" }, needs: ["temperature", "probability-p"] },
  { id: "diffusion", name: "Diffusion", branch: "fluids", ring: 2, what: "Random motion produces net spreading down a concentration gradient in a simple uniform medium. With constant diffusivity, typical displacement grows with the square root of time.", compute: "The diffusion equation connects random walks to a continuum model.", life: { detail: "Explore how time and permeability change concentrations in the Biology diffusion model.", href: "/biology#bio-diffusion" }, needs: ["brownian"] },
  { id: "osmosis", name: "Osmosis", branch: "fluids", ring: 2, what: "Water moves across a selectively permeable membrane in response to a difference in water chemical potential. Solutes and pressure both affect the direction and balance.", world: "Water balance in cells and turgor in plants.", life: { detail: "A cell's volume depends on which substances can cross its membrane and on the conditions on each side.", href: "/biology#cells" }, needs: ["diffusion", "pressure"] },
  { id: "poiseuille", name: "Flow through a tube", branch: "fluids", ring: 3, what: "For steady laminar flow of a Newtonian fluid in a rigid circular tube, Poiseuille's law gives Q = π ΔP r⁴ / (8 η L). Radius strongly affects flow resistance.", life: { detail: "This is a useful starting model for circulation. Pulsation, flexible vessel walls and blood's material properties limit the approximation.", href: "/biology#systems" }, needs: ["viscosity", "pressure", "reynolds"] },
  { id: "chemical-potential", name: "Chemical potential", branch: "thermo", ring: 3, what: "At fixed temperature and pressure, the change in Gibbs free energy per added amount of a species. Differences help determine the direction of transport and reaction.", life: { detail: "Concentration differences contribute to the driving forces for transport and chemical reactions inside cells.", href: "/biology#energy" }, needs: ["free-energy"] },
  { id: "electrochemical", name: "Electrochemical gradients", branch: "em", ring: 3, what: "An ion responds to both chemical potential and electrical potential. Together they determine its electrochemical driving force.", life: { detail: "Ion gradients support membrane transport and nerve signals; proton gradients help drive ATP synthesis.", href: "/biology#systems" }, needs: ["chemical-potential", "field"] },
  { id: "capacitance", name: "Capacitance & membranes", branch: "em", ring: 2, what: "A capacitor stores separated charge with Q = C V. An insulating membrane between conducting fluids can be modeled as a capacitor with conducting channels alongside it.", compute: "Equivalent circuits model how membrane voltage changes with currents and time.", life: { detail: "Membrane capacitance and ion channels are part of the physical basis of a neuron's electrical response.", href: "/biology#systems" }, needs: ["current", "field"] },
  { id: "molecular-motors", name: "Molecular motors", branch: "mechanics", ring: 3, what: "Protein machines couple chemical free-energy changes to directed motion. Cytoskeletal motors such as myosin and kinesin use ATP-dependent cycles to perform mechanical work.", life: { detail: "Motor proteins move cargo within cells and generate forces in muscles. Thermal fluctuations remain part of their environment.", href: "/biology#cells" }, needs: ["work-power", "free-energy", "brownian"] },
];

export const ideaById = new Map(ideas.map(idea => [idea.id, idea]));
