// Keep these two in step: reviewedOnISO fills the <time datetime> attribute.
export const reviewedOnISO = "2026-09-19";
export const reviewedOn = "September 19, 2026";

export const chapters = [
  ["history", "How we got here"], ["what-is-ai", "What AI means"], ["ai-to-ml", "From AI to ML"],
  ["how-ai-works", "How a system works"], ["generative-ai", "Inside generative AI"],
  ["ai-today", "AI today & trends"], ["tools", "The tool landscape"],
  ["judgment", "Evaluate the result"], ["practice", "Practice & review"], ["next", "Your next steps"],
] as const;

export const history = [
  { year: "1950", title: "Make the question testable", people: "Alan Turing", text: "Computing Machinery and Intelligence introduces the imitation game: evaluate a machine through its behavior in conversation. This frames a research question; it does not establish that fluent behavior proves consciousness.", lesson: "Define observable performance before making a claim about intelligence.", source: "Turing’s original paper", href: "https://academic.oup.com/mind/article/LIX/236/433/986238" },
  { year: "1956", title: "A field gets a name", people: "The Dartmouth research project", text: "The Dartmouth summer project helps establish artificial intelligence as a research field. Its ambition is much wider than chatbots: reasoning, learning, language, and solving problems with machines.", lesson: "AI is the broad field. Any one technique covers only part of it.", source: "Dartmouth’s historical account", href: "https://home.dartmouth.edu/news/2026/06/birth-artificial-intelligence" },
  { year: "1958", title: "Learning from examples", people: "Frank Rosenblatt and the perceptron", text: "Rosenblatt demonstrates a system that adjusts connections to distinguish input patterns. Early learning machines make the central ML idea concrete: useful behavior can come from adapting parameters to examples.", lesson: "Learning is not new, and a simple learned model is not a modern deep network.", source: "Cornell’s perceptron history", href: "https://news.cornell.edu/stories/2019/09/professors-perceptron-paved-way-ai-60-years-too-soon" },
  { year: "1973", title: "Ambition meets limits", people: "The Lighthill controversy", text: "Criticism of AI’s progress and its ability to scale contributed to a difficult period for British AI research. The history of AI includes setbacks and periods known as AI winters, alongside continued work.", lesson: "Success on a demonstration does not establish that a method scales to the real world.", source: "University of Edinburgh’s AI history", href: "https://www.aiai.ed.ac.uk/events/edcomphistory2007/AIhistory.htm" },
  { year: "1970s–80s", title: "Put specialist knowledge into rules", people: "MYCIN and expert systems", text: "Expert systems encode domain knowledge as rules and use an inference engine to apply it. MYCIN becomes a major research example. Building and maintaining the knowledge base is a central engineering challenge.", lesson: "An AI system can use human-authored knowledge without learning its rules from a dataset.", source: "Buchanan & Shortliffe’s MYCIN book", href: "https://www.shortliffe.net/Buchanan-Shortliffe-1984/MYCIN%20Book.htm" },
  { year: "1986", title: "Learn internal representations", people: "Rumelhart, Hinton, and Williams", text: "An influential paper shows how backpropagation trains hidden units to represent useful features. Backpropagation computes gradients; an optimization procedure uses them to adjust weights.", lesson: "A network can learn both intermediate features and a final prediction.", source: "The backpropagation paper", href: "https://www.nature.com/articles/323533a0" },
  { year: "1997", title: "Search reaches championship level", people: "IBM Deep Blue", text: "Deep Blue defeats world chess champion Garry Kasparov in a match. Specialized search, evaluation, and computing power produce extraordinary performance within a well-defined domain.", lesson: "Being excellent at chess does not imply competence at every other task.", source: "IBM’s Deep Blue history", href: "https://www.ibm.com/history/deep-blue" },
  { year: "2012", title: "Deep learning changes computer vision", people: "Krizhevsky, Sutskever, and Hinton", text: "The AlexNet work demonstrates strong image-classification results using a deep convolutional network. Large labeled datasets, GPU computation, and training techniques make a powerful combination.", lesson: "Progress depends on data and computation as well as the model’s architecture.", source: "The ImageNet / AlexNet paper", href: "https://papers.nips.cc/paper_files/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html" },
  { year: "2016", title: "Combine learning with search", people: "DeepMind’s AlphaGo", text: "AlphaGo defeats Lee Sedol in Go. Its approach combines neural networks, learning, and search, illustrating how different AI methods can work together in one system.", lesson: "The choice is often a combination of methods, rather than one technique replacing all others.", source: "DeepMind’s AlphaGo account", href: "https://deepmind.google/research/alphago/" },
  { year: "2017", title: "Attention becomes an architecture", people: "Vaswani and collaborators", text: "Attention Is All You Need introduces the Transformer for sequence transduction. Attention lets representations incorporate information from other positions; Transformers become foundational to many later language and multimodal models.", lesson: "An architecture is a design for computation, not a complete application.", source: "The Transformer paper", href: "https://arxiv.org/abs/1706.03762" },
  { year: "2022", title: "Conversational generative AI reaches users", people: "The launch of ChatGPT", text: "OpenAI releases ChatGPT on November 30, 2022. A conversational interface makes a trained language model directly accessible to a broad audience, while also exposing its tendency to produce plausible errors.", lesson: "A useful interface can change adoption without making the underlying model infallible.", source: "The original launch announcement", href: "https://openai.com/index/chatgpt/" },
  { year: "2026", title: "From impressive answers to useful systems", people: "An expanding and uneven landscape", text: "Stanford’s 2026 AI Index documents progress across language, vision, reasoning, and agentic tasks, alongside uneven reliability. The practical question becomes how well a complete system performs in its intended setting.", lesson: "Evaluate the task, data, tools, and operating conditions together.", source: "Stanford AI Index 2026", href: "https://hai.stanford.edu/ai-index/2026-ai-index-report" },
];

export const trends = [
  { title: "Models work across modalities", text: "Text, images, audio, and video increasingly share one interface. This enables tasks such as asking about a diagram or discussing a document by voice. Supported inputs and outputs vary by product and model.", implication: "Check the modality you actually need, not just the model’s headline label.", source: "Gemini’s current capabilities", href: "https://gemini.google/overview/" },
  { title: "Agents connect models to actions", text: "Systems can combine a model with tools, state, and a loop that chooses subsequent actions. This expands the task from producing text to navigating a workflow, where tool failures and incorrect actions also matter.", implication: "Measure task completion and inspect actions; a fluent explanation is not proof of execution.", source: "Anthropic: workflows and agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
  { title: "Reasoning gains remain uneven", text: "The 2026 AI Index reports stronger performance on demanding benchmarks alongside weaknesses on seemingly simpler tasks. Benchmark success does not establish dependable performance on every input or a particular workplace task.", implication: "Use your own representative evaluation set, including exceptions and failure cases.", source: "Stanford AI Index 2026", href: "https://hai.stanford.edu/ai-index/2026-ai-index-report" },
  { title: "Retrieval connects answers to evidence", text: "Retrieval-augmented generation supplies relevant documents at answer time. It offers a way to use changing or specialized information without fitting all those facts into a fresh model update.", implication: "Evaluate whether retrieval found the right passage and whether the answer actually follows it.", source: "The RAG research paper", href: "https://arxiv.org/abs/2005.11401" },
  { title: "Deployment choices are broadening", text: "Model hubs and local runtimes make it possible to explore downloadable models as well as hosted services. Access to weights, hardware needs, and license terms differ; downloadable does not automatically mean unrestricted.", implication: "Compare capability, memory, latency, operational effort, and the actual license.", source: "Hugging Face Hub documentation", href: "https://huggingface.co/docs/hub/en/index" },
  { title: "Evaluation becomes part of the product", text: "The NIST AI Risk Management Framework treats evaluation and risk management as ongoing work across the system lifecycle. Reliability, bias, and the context of use need attention beyond the initial demonstration.", implication: "Monitor changes after deployment and define when a person should take over.", source: "NIST AI Risk Management Framework", href: "https://www.nist.gov/itl/ai-risk-management-framework" },
];

export type ToolCategory = "Assistants" | "Research" | "Coding" | "Creative" | "Build models" | "Deploy & orchestrate";
export type AITool = { name: string; category: ToolCategory; kind: string; use: string; check: string; href: string };
export const toolCategories: ToolCategory[] = ["Assistants", "Research", "Coding", "Creative", "Build models", "Deploy & orchestrate"];
export const aiTools: AITool[] = [
  { name: "ChatGPT", category: "Assistants", kind: "Hosted application", use: "Conversational help with writing, explanation, analysis, and tasks involving supported tools.", check: "Check enabled tools, account settings, and evidence behind factual answers.", href: "https://chatgpt.com/overview/" },
  { name: "Claude", category: "Assistants", kind: "Hosted application", use: "Work with language, documents, analysis, and coding through a conversational assistant.", check: "Check document limits, connected tools, and the behavior required by your task.", href: "https://claude.com/product/overview" },
  { name: "Gemini", category: "Assistants", kind: "Hosted application", use: "A Google assistant for questions and tasks across supported text and multimodal inputs.", check: "Check which integrations and input types are available in your account and region.", href: "https://gemini.google/overview/" },
  { name: "Perplexity", category: "Research", kind: "Search and answer application", use: "Find information through web-backed answers and source links.", check: "Open the cited page and verify that it supports the specific claim.", href: "https://www.perplexity.ai/help-center/en/articles/10352155-what-is-perplexity" },
  { name: "GitHub Copilot", category: "Coding", kind: "Coding assistant and agent", use: "Code suggestions, explanations, edits, and agent workflows within supported development environments.", check: "Review diffs, run tests, and verify repository and tool permissions.", href: "https://github.com/features/copilot" },
  { name: "Cursor", category: "Coding", kind: "AI coding environment", use: "Explore a codebase and make changes through an editor with AI assistance and agent features.", check: "Check the scope of proposed edits and validate the resulting behavior.", href: "https://cursor.com/" },
  { name: "Adobe Firefly", category: "Creative", kind: "Generative creative application", use: "Generate and edit visual assets using supported image and video workflows.", check: "Review output quality, usage terms, and the requirements of your intended project.", href: "https://www.adobe.com/products/firefly.html" },
  { name: "Runway", category: "Creative", kind: "Generative media platform", use: "Create and transform media, including video, with generative models and editing tools.", check: "Check continuity, controllability, export options, and applicable usage terms.", href: "https://runway.com/" },
  { name: "scikit-learn", category: "Build models", kind: "Python ML library", use: "Fit classical models, compose preprocessing pipelines, and perform model selection and evaluation.", check: "Keep preprocessing inside training folds and choose metrics suited to the task.", href: "https://scikit-learn.org/stable/" },
  { name: "PyTorch", category: "Build models", kind: "Deep learning framework", use: "Build tensor computations and neural networks with automatic differentiation.", check: "Check device support, tensor shapes, training cost, and reproducibility.", href: "https://pytorch.org/" },
  { name: "TensorFlow / Keras", category: "Build models", kind: "Deep learning framework and API", use: "Define, train, evaluate, and deploy neural models; used in ML Week 4.", check: "Match the output, labels, and loss, and save the required preprocessing.", href: "https://www.tensorflow.org/" },
  { name: "Hugging Face Hub", category: "Build models", kind: "Model and dataset hub", use: "Discover model weights, datasets, model cards, and demonstrations.", check: "Inspect the model card, data provenance, license, and task-specific limitations.", href: "https://huggingface.co/docs/hub/en/index" },
  { name: "Ollama", category: "Deploy & orchestrate", kind: "Model runtime", use: "Run supported models through a local interface or supported cloud features.", check: "Local models still require suitable memory and compute. Check whether your chosen route is local or remote.", href: "https://docs.ollama.com/" },
  { name: "LangGraph", category: "Deploy & orchestrate", kind: "Workflow and agent framework", use: "Coordinate stateful model-and-tool workflows with control over execution.", check: "You still need a model, tools, evaluation, and a deployment plan.", href: "https://docs.langchain.com/oss/python/langgraph/overview" },
  { name: "Amazon Bedrock", category: "Deploy & orchestrate", kind: "Managed cloud platform", use: "Access supported foundation models and build generative AI applications and agents on AWS.", check: "Check model availability, region, data handling, and usage costs.", href: "https://aws.amazon.com/bedrock/" },
  { name: "Gemini Enterprise Agent Platform", category: "Deploy & orchestrate", kind: "Managed cloud platform · formerly Vertex AI", use: "Google Cloud’s platform for building and operating AI models, applications, and agents.", check: "Check supported services, region, evaluation options, and operating costs.", href: "https://cloud.google.com/products/gemini-enterprise-agent-platform" },
];

export const reviewQuestions = [
  ["Can an AI system work without machine learning?", "Yes. Search, planning, logic, and human-authored expert rules can produce useful AI behavior without fitting a model from examples. Many real systems combine these with learned components."],
  ["How do AI, ML, deep learning, and generative AI relate?", "AI is the broad field. ML is an approach within it that learns from data or experience. Deep learning is a family of ML methods based on multilayer neural networks. Generative AI describes a capability: creating outputs such as text or images. Modern generative systems often use deep learning; an LLM is one kind of model, not a synonym for all AI."],
  ["What changes during training, and what happens during inference?", "Training adjusts learned parameters according to data and an objective. Inference applies a fitted model to an input. An ordinary request can change context or application state without changing model weights."],
  ["Does a confident answer mean a model checked the facts?", "No. Fluency and confidence in wording do not establish correctness. Check source support, calculations, and task results separately."],
  ["What is the difference between prompting, retrieval, and fine-tuning?", "Prompting changes the instructions or context provided for a request. Retrieval selects external information and adds it to that context. Fine-tuning updates model parameters using additional training examples. They address different needs and can be combined."],
  ["What makes an agent different from a text-only response?", "An agentic system can choose actions, call tools, observe results, and continue toward an objective. The surrounding software controls permissions, state, and execution. A model claiming that an action happened is not enough; the tool result must confirm it."],
  ["Why does a simple baseline belong in an AI project?", "It makes improvement measurable. A fixed rule, majority-class predictor, or simple model may already solve enough of the task. Complexity needs to earn its additional cost and maintenance."],
  ["What should you know before selecting a tool?", "Define the task and expected output, representative inputs, acceptable errors, data constraints, and a time or cost budget. Then compare actual results using the same examples."],
];

export const glossary = [
  ["Model", "A computational mapping with a particular structure and, for learned models, fitted parameters."],
  ["Parameter", "A value learned during training, such as a weight or bias."],
  ["Hyperparameter", "A setting chosen for the model or training procedure, such as tree depth or learning rate."],
  ["Feature", "An input measurement or representation used to make a prediction."],
  ["Label", "A target answer supplied for a supervised learning example."],
  ["Loss", "A numeric training objective that measures a kind of prediction error."],
  ["Token", "A unit in a model’s input or output representation; a text token need not be a whole word."],
  ["Embedding", "A vector representation used to encode information about an input."],
  ["Context window", "The amount of token context a model can process in one request, subject to its limits."],
  ["Inference", "Using a fitted model to compute an output."],
  ["Hallucination", "A plausible generated claim that is unsupported or incorrect."],
  ["Evaluation", "Measuring performance on defined tasks, examples, and criteria."],
];

