export type RegionId = "frontal" | "parietal" | "temporal" | "occipital" | "cerebellum" | "brainstem" | "thalamus" | "hypothalamus" | "hippocampus" | "spinal";
export type BrainRegion = {
 id:RegionId; name:string; subtitle:string; color:string; inside:boolean;
 position:string; role:string; example:string; connection:string; remember:string;
};
export const regions:BrainRegion[] = [
 {id:"frontal",name:"Frontal lobe",subtitle:"Plan · choose · move",color:"#8cd7b9",inside:false,position:"The front part of each cerebral hemisphere.",role:"Frontal networks contribute to planning, decisions, working memory, and voluntary movement. The primary motor cortex lies toward the back of this lobe.",example:"Choosing to reach for a cup draws on frontal activity together with sensory and motor networks elsewhere.",connection:"Motor commands interact with the basal ganglia and cerebellum, then reach brainstem and spinal circuits.",remember:"A lobe is not a single-purpose module. Planning and behavior depend on distributed networks."},
 {id:"parietal",name:"Parietal lobe",subtitle:"Feel · locate · integrate",color:"#9db5f3",inside:false,position:"Behind the frontal lobe, toward the upper rear of the cerebrum.",role:"Parietal networks combine bodily and spatial information. The primary somatosensory cortex receives organized information about touch and the body.",example:"Finding your hand without looking and judging a cup’s location involve body and spatial representations.",connection:"Works with visual, somatosensory, and frontal networks to guide attention and action.",remember:"Sensory experience is constructed across pathways; it is not a raw picture stored in one place."},
 {id:"temporal",name:"Temporal lobe",subtitle:"Hear · recognize · remember",color:"#e8b282",inside:false,position:"The lower side of each cerebral hemisphere, near the temples.",role:"Temporal regions contribute to hearing, recognition, language, and memory. Different subregions participate in different functions.",example:"Recognizing a familiar voice combines sound processing with learned associations.",connection:"The hippocampus lies in the medial temporal region and interacts with widespread cortical networks.",remember:"Hearing, understanding language, and remembering are related but distinct processes."},
 {id:"occipital",name:"Occipital lobe",subtitle:"Process visual information",color:"#cea2df",inside:false,position:"The back of each cerebral hemisphere.",role:"Contains primary visual cortex and other visual processing areas. Visual information is subsequently processed through broader networks.",example:"Edges and orientations in a scene contribute to identifying objects and judging where they are.",connection:"A major route runs from retina through the thalamus to visual cortex; further pathways reach temporal and parietal regions.",remember:"Vision begins in the eyes, but seeing involves many connected stages in the brain."},
 {id:"cerebellum",name:"Cerebellum",subtitle:"Coordinate · predict · refine",color:"#e2cc82",inside:false,position:"Below the back of the cerebrum, behind the brainstem.",role:"Supports coordination, balance, and motor learning. Its contributions also extend to some cognitive processes.",example:"Adjusting the timing of a practiced movement involves cerebellar circuits.",connection:"Compares and combines information through loops with the cortex, brainstem, and spinal systems.",remember:"It helps refine movement; it is not the sole origin of voluntary motor commands."},
 {id:"brainstem",name:"Brainstem",subtitle:"Connect · regulate · sustain",color:"#e29ba5",inside:false,position:"Below the cerebrum, in front of the cerebellum; continuous with the spinal cord.",role:"Includes the midbrain, pons, and medulla. Its many nuclei and pathways support arousal, cranial-nerve functions, and vital regulation.",example:"Breathing regulation depends on brainstem circuits interacting with chemical and sensory feedback.",connection:"Ascending and descending pathways pass between brain and spinal cord; many cranial nerves connect here.",remember:"The brainstem contains many circuits. It is much more than a cable between two structures."},
 {id:"thalamus",name:"Thalamus",subtitle:"Route · regulate · coordinate",color:"#90d7e8",inside:true,position:"Paired structures near the center of the brain, above the brainstem.",role:"Thalamic nuclei interact with cortex in sensory, motor, and cognitive loops. Many sensory pathways pass through it.",example:"Visual and somatosensory signals use different thalamic nuclei on their way to cortical networks.",connection:"Extensive two-way connections link thalamic nuclei and cerebral cortex.",remember:"It is not a passive relay for every sense. Olfactory pathways are a familiar exception to the simple relay story."},
 {id:"hypothalamus",name:"Hypothalamus",subtitle:"Regulate the internal world",color:"#f3aa78",inside:true,position:"Below the thalamus, close to the pituitary connection.",role:"Coordinates aspects of temperature, hunger, thirst, circadian timing, autonomic activity, and hormone regulation.",example:"Maintaining body temperature involves signals about internal conditions and coordinated responses.",connection:"Connects neural regulation with endocrine signaling through its relationship with the pituitary.",remember:"Homeostasis involves interacting feedback systems, rather than one fixed switch."},
 {id:"hippocampus",name:"Hippocampus",subtitle:"Form memories · map context",color:"#d7a3be",inside:true,position:"A curved structure in the medial temporal region of each hemisphere.",role:"Important for forming and organizing some kinds of memory, especially events and contexts, and for spatial representations.",example:"Remembering a recent experience and where it happened depends on a wider network that includes the hippocampus.",connection:"Interacts with nearby medial temporal structures and distributed cortical networks.",remember:"It is not a storage box for all memories; different forms of learning depend on different systems."},
 {id:"spinal",name:"Spinal cord",subtitle:"Carry signals · organize reflexes",color:"#a5cdb6",inside:false,position:"Extends from the brainstem through the vertebral canal.",role:"Carries ascending and descending information and contains circuits that organize reflexes and aspects of movement.",example:"A withdrawal response can recruit spinal circuits without waiting for a conscious decision.",connection:"Spinal nerves connect peripheral receptors and muscles with the central nervous system.",remember:"A spinal reflex still uses the central nervous system. The brain can influence these circuits."},
];
export const regionById=Object.fromEntries(regions.map(r=>[r.id,r])) as Record<RegionId,BrainRegion>;
export const regionIndex=(id:RegionId)=>regions.findIndex(r=>r.id===id);
export const challenges:{question:string;answer:RegionId;why:string}[]=[
 {question:"Find the lobe at the back of the cerebrum that contains primary visual cortex.",answer:"occipital",why:"The occipital lobe contains primary visual cortex; vision also depends on pathways beyond it."},
 {question:"Find the structure behind the brainstem that helps coordinate and refine movements.",answer:"cerebellum",why:"The cerebellum contributes to timing, coordination, balance, and motor learning."},
 {question:"Look inside: which paired structure is important for event and context memory?",answer:"hippocampus",why:"The hippocampus works with cortical and other medial temporal structures; memory is distributed."},
 {question:"Find the central nervous system structure that contains withdrawal-reflex circuits below the brain.",answer:"spinal",why:"Spinal circuits can coordinate a withdrawal response, while ascending signals also reach the brain."},
 {question:"Look inside: which structure helps coordinate thirst, temperature, and endocrine regulation?",answer:"hypothalamus",why:"The hypothalamus links internal-state monitoring with autonomic and hormonal responses."},
];
export const references=[
 {name:"NINDS · Brain Basics",url:"https://www.ninds.nih.gov/health-information/public-education/brain-basics",detail:"Introductions to brain organization and neuronal communication."},
 {name:"NICHD · Parts of the nervous system",url:"https://www.nichd.nih.gov/health/topics/neuro/conditioninfo/parts",detail:"Central and peripheral systems, neurons, and supporting glial cells."},
 {name:"Society for Neuroscience · Mapping the Brain",url:"https://www.brainfacts.org/Brain-Anatomy-and-Function/Anatomy/2012/Mapping-the-Brain",detail:"Cortical lobes and deeper structures in their anatomical context."},
 {name:"NIH/NIMH · Get to Know Your Brain",url:"https://www.nimh.nih.gov/news/media/2023/get-to-know-your-brain",detail:"An introductory tour of major brain regions."},
 {name:"Purves et al. · Myelination",url:"https://www.ncbi.nlm.nih.gov/books/NBK10921/",detail:"Why myelin changes how an axon conducts a signal."},
 {name:"Purves et al. · Spinal reflex circuitry",url:"https://www.ncbi.nlm.nih.gov/books/NBK10809/",detail:"Local spinal circuits and their relationship to sensory and motor neurons."},
];
