"use client";
import { useState } from "react";
import type { ReactNode } from "react";
import { calibration, diffuse, estimateClean, gaussianKL, lstmStep, softmax, tdUpdate } from "./lab-math";

function Slider({label,value,set,min,max,step=.05}:{label:string;value:number;set:(n:number)=>void;min:number;max:number;step?:number}) {
 return <label className="dc-control"><span>{label}<output>{Number(value.toFixed(3))}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>;
}
function Frame({title,children}:{title:string;children:ReactNode}) {return <div className="dc-lab"><p className="dc-eyebrow">INTERACTIVE / CHANGE ONE ASSUMPTION</p><h3>{title}</h3>{children}</div>;}
function Readouts({items}:{items:[string,string][]}) {return <dl className="dc-readouts">{items.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>;}
function Bars({labels,values}:{labels:string[];values:number[]}) {return <div className="dc-bars">{values.map((v,i)=><div className="dc-bar-row" key={i}><span>{labels[i]}</span><div className="dc-bar-track"><i style={{width:`${(100*v).toFixed(2)}%`}}/></div><output>{v.toFixed(4)}</output></div>)}</div>;}
function Plot({series,min=-1,max=1,label}:{series:{name:string;values:number[];color:string}[];min?:number;max?:number;label:string}) {
 const r2=(value:number)=>Number(value.toFixed(2));
 const x=(i:number,n:number)=>r2(45+510*i/Math.max(1,n-1)),y=(v:number)=>r2(210-165*(v-min)/(max-min));
 return <svg viewBox="0 0 600 250" className="dc-plot" role="img" aria-label={label}>
  {[min,(min+max)/2,max].map(v=><g key={v}><line x1="45" x2="565" y1={y(v)} y2={y(v)} stroke="currentColor" strokeOpacity=".15"/><text x="4" y={y(v)+4}>{v.toFixed(1)}</text></g>)}
  {series.map((s,i)=><g key={s.name}><text x={45+i*170} y="22" style={{fill:s.color}}>{s.name}</text><polyline fill="none" stroke={s.color} strokeWidth="2.5" points={s.values.map((v,j)=>`${x(j,s.values.length)},${y(v)}`).join(" ")}/></g>)}
  <text x="45" y="238">start</text><text x="530" y="238">end</text>
 </svg>;
}

export function MemoryLab() {
 const [forget,setForget]=useState(.9),[input,setInput]=useState(.25),[candidate,setCandidate]=useState(.4),[output,setOutput]=useState(.7),[steps,setSteps]=useState(20);
 const state=lstmStep(.8,forget,input,candidate,output);
 const retention=Array.from({length:steps+1},(_,i)=>Math.pow(forget,i));
 return <Frame title="Retain, write, expose"><p>Start with cell state 0.8. Change fixed gate values for one update, then inspect the direct retention path across repeated steps without new writing.</p><div className="dc-controls"><Slider label="Forget gate f" value={forget} set={setForget} min={0} max={1} step={.01}/><Slider label="Input gate i" value={input} set={setInput} min={0} max={1}/><Slider label="Candidate g" value={candidate} set={setCandidate} min={-1} max={1}/><Slider label="Output gate o" value={output} set={setOutput} min={0} max={1}/><Slider label="Retention steps" value={steps} set={setSteps} min={1} max={50} step={1}/></div><Readouts items={[["Updated cell c",state.cell.toFixed(4)],["Exposed hidden h",state.hidden.toFixed(4)],[`Direct retention f^${steps}`,Math.pow(forget,steps).toFixed(5)]]}/><Plot series={[{name:"Direct retention",values:retention,color:"var(--dc-teal)"}]} min={0} max={1} label={`Direct cell-state retention decreases from 1 to ${retention.at(-1)?.toFixed(5)} over ${steps} steps.`}/><p className="dc-caption">The plot holds gates fixed and isolates one path. It is not the full LSTM Jacobian, which also includes learned gate dependencies.</p></Frame>;
}
export function AttentionLab() {
 const [first,setFirst]=useState(2),[temperature,setTemperature]=useState(1),[masked,setMasked]=useState(false);
 const weights=softmax([first,.5,masked?-Infinity:-1],temperature),values=[1,3,-2];
 return <Frame title="One query, three possible sources"><p>Scores start at [2, 0.5, −1]. Values are [1, 3, −2]. The first score, temperature, and final-key mask change the actual softmax and retrieved value.</p><div className="dc-controls"><Slider label="First score" value={first} set={setFirst} min={-3} max={4} step={.1}/><Slider label="Temperature" value={temperature} set={setTemperature} min={.1} max={3} step={.1}/></div><label className="dc-check"><input type="checkbox" checked={masked} onChange={e=>setMasked(e.target.checked)}/>Block the third key before softmax</label><Bars labels={["Key 1","Key 2",masked?"Key 3 (blocked)":"Key 3"]} values={weights}/><Readouts items={[["Weight sum",weights.reduce((a,b)=>a+b,0).toFixed(4)],["Weighted value",weights.reduce((a,b,i)=>a+b*values[i],0).toFixed(5)]]}/><p className="dc-caption">These are already scaled scores. The temperature is an extra teaching control; a masked entry is excluded before normalization.</p></Frame>;
}
export function ContrastiveLab() {
 const [positive,setPositive]=useState(.8),[negative,setNegative]=useState(.2),[temperature,setTemperature]=useState(.5),[count,setCount]=useState(6);
 const probabilities=softmax([positive,...Array(count).fill(negative)],temperature);
 return <Frame title="A positive competes with negative candidates"><p>This is one anchor’s loss. Its self-comparison is excluded; the positive remains in the denominator. All negatives share one similarity here to isolate the effect of count and temperature.</p><div className="dc-controls"><Slider label="Positive cosine similarity" value={positive} set={setPositive} min={-1} max={1}/><Slider label="Negative cosine similarity" value={negative} set={setNegative} min={-1} max={1}/><Slider label="Temperature τ" value={temperature} set={setTemperature} min={.05} max={1.5}/><Slider label="Number of negatives" value={count} set={setCount} min={1} max={30} step={1}/></div><Bars labels={["Positive","All negatives"]} values={[probabilities[0],1-probabilities[0]]}/><Readouts items={[["Anchor loss",(-Math.log(probabilities[0])).toFixed(4)],["Equal-score baseline",Math.log(count+1).toFixed(4)],["Positive probability",probabilities[0].toFixed(4)]]}/><p className="dc-caption">Set both similarities equal: changing temperature cannot resolve identical scores. This scalar lab does not simulate an encoder training run.</p></Frame>;
}
export function VAELab() {
 const [mu,setMu]=useState(1),[logvar,setLogvar]=useState(0),[eps,setEps]=useState(-.5),[beta,setBeta]=useState(1);
 const std=Math.exp(logvar/2),z=mu+std*eps,kl=gaussianKL(mu,logvar);
 const decoderMean=.8*z, target=.5,variance=.25;
 const nll=.5*((target-decoderMean)**2/variance+Math.log(2*Math.PI*variance));
 const xs=Array.from({length:81},(_,i)=>-5+i/8),density=(x:number,m:number,s:number)=>Math.exp(-.5*((x-m)/s)**2)/(s*Math.sqrt(2*Math.PI));
 return <Frame title="Sample a latent and inspect its cost"><p>One latent dimension, a fixed toy decoder mean 0.8z, observation x=0.5, and Gaussian observation variance 0.25. The plotted posterior is compared with a standard-normal prior.</p><div className="dc-controls"><Slider label="Posterior mean μ" value={mu} set={setMu} min={-2} max={2}/><Slider label="Log-variance" value={logvar} set={setLogvar} min={-2} max={2}/><Slider label="Noise draw ε" value={eps} set={setEps} min={-2} max={2}/><Slider label="KL weight β" value={beta} set={setBeta} min={0} max={3}/></div><Plot min={0} max={1.2} label="Gaussian probability densities from latent coordinate minus five to five." series={[{name:"Prior",values:xs.map(x=>density(x,0,1)),color:"var(--dc-accent)"},{name:"Posterior",values:xs.map(x=>density(x,mu,std)),color:"var(--dc-teal)"}]}/><Readouts items={[["Latent sample z",z.toFixed(4)],["KL (nats)",kl.toFixed(4)],["Sampled recon NLL",nll.toFixed(4)],["NLL + β KL",(nll+beta*kl).toFixed(4)]]}/><p className="dc-caption">A single ε gives a Monte Carlo reconstruction term. KL is analytic and does not depend on this draw. The browser is evaluating equations, not training the toy decoder.</p></Frame>;
}
export function GANLab() {
 const [logit,setLogit]=useState(-5); const p=1/(1+Math.exp(-logit));
 const points=Array.from({length:81},(_,i)=>-8+i*.2),sigmoid=(v:number)=>1/(1+Math.exp(-v));
 return <Frame title="Inspect the generator's fake-logit gradient"><div className="dc-controls"><Slider label="Discriminator fake logit" value={logit} set={setLogit} min={-8} max={8} step={.1}/></div><Plot min={-1} max={0} label="Generator loss derivatives with respect to fake logit, from minus eight to eight." series={[{name:"Minimax",values:points.map(v=>-sigmoid(v)),color:"var(--dc-accent)"},{name:"Non-saturating",values:points.map(v=>sigmoid(v)-1),color:"var(--dc-teal)"}]}/><Readouts items={[["D(fake)",p.toFixed(5)],["Minimax dL/da",(-p).toFixed(5)],["Non-saturating dL/da",(p-1).toFixed(5)]]}/><p>Both derivatives are negative, so gradient descent pushes this logit upward. When D strongly rejects a fake, the non-saturating objective retains a much larger logit-level signal.</p><p className="dc-caption">This is one link in the chain rule. The full generator parameter gradient also depends on both networks’ Jacobians.</p></Frame>;
}
const CLEAN=Array.from({length:40},(_,i)=>.65*Math.sin(i*.25)+.25*Math.cos(i*.7));
// Fixed Box–Muller draws keep SSR and hydration deterministic.
const NOISE=Array.from({length:40},(_,i)=>Math.sqrt(-2*Math.log(((i*37+19)%97+1)/99))*Math.cos(2*Math.PI*((i*53+11)%89)/89));
export function DiffusionLab() {
 const [alpha,setAlpha]=useState(.64),[quality,setQuality]=useState(1);
 const noisy=CLEAN.map((v,i)=>diffuse(v,NOISE[i],alpha)),restored=noisy.map((v,i)=>estimateClean(v,quality*NOISE[i],alpha));
 const mse=restored.reduce((s,v,i)=>s+(v-CLEAN[i])**2,0)/CLEAN.length;
 const bound=Math.max(2,...noisy.map(Math.abs),...restored.map(Math.abs));
 return <Frame title="Corrupt a signal, then test an oracle estimate"><p>The same fixed Gaussian noise draw is used at every slider position. A multiplier of 1 uses the exact known noise; other values deliberately introduce prediction error.</p><div className="dc-controls"><Slider label="Cumulative ᾱ" value={alpha} set={setAlpha} min={.01} max={1} step={.01}/><Slider label="Noise estimate multiplier" value={quality} set={setQuality} min={0} max={1.5}/></div><Plot min={-bound} max={bound} label="Clean signal, noisy observation, and estimated clean signal over forty positions." series={[{name:"Original",values:CLEAN,color:"var(--dc-accent)"},{name:"Noisy",values:noisy,color:"var(--color-muted)"},{name:"Estimated clean",values:restored,color:"var(--dc-teal)"}]}/><Readouts items={[["Signal coefficient",Math.sqrt(alpha).toFixed(4)],["Noise coefficient",Math.sqrt(1-alpha).toFixed(4)],["Reconstruction MSE",mse.toFixed(6)]]}/><p className="dc-caption">Exact recovery at multiplier 1 is an algebra check using oracle noise. A trained denoiser does not know that noise at generation time. Small ᾱ amplifies prediction error in this x₀ conversion.</p></Frame>;
}
const CAL_LOGITS=Array.from({length:60},(_,i)=>{const a=.5+(i%10)*.45;return i%2?[a,0]:[0,a];});
const CAL_LABELS=Array.from({length:60},(_,i)=>{const predicted=i%2?0:1;return i%5<3?predicted:1-predicted;});
export function CalibrationLab() {
 const [temperature,setTemperature]=useState(1),[bins,setBins]=useState(5),report=calibration(CAL_LOGITS,CAL_LABELS,temperature,bins);
 return <Frame title="Confidence changes while accuracy stays fixed"><p>A fixed illustrative set contains 60 two-class predictions. Adjust temperature and bin count, then compare confidence with observed correctness. This demonstration does not fit temperature on a test set.</p><div className="dc-controls"><Slider label="Temperature T" value={temperature} set={setTemperature} min={.25} max={5} step={.05}/><Slider label="Confidence bins" value={bins} set={setBins} min={3} max={10} step={1}/></div><Readouts items={[["Accuracy",`${(100*report.accuracy).toFixed(1)}%`],["NLL",report.nll.toFixed(4)],["ECE",report.ece.toFixed(4)]]}/><div className="dc-table-scroll" tabIndex={0} role="region" aria-label="Reliability bins"><table><thead><tr><th>Confidence bin</th><th>Count</th><th>Mean confidence</th><th>Accuracy</th></tr></thead><tbody>{report.bins.map((b,i)=><tr key={i}><th scope="row">{b.lower.toFixed(2)}–{b.upper.toFixed(2)}</th><td>{b.count}</td><td>{b.count?b.confidence.toFixed(3):"—"}</td><td>{b.count?b.accuracy.toFixed(3):"—"}</td></tr>)}</tbody></table></div><p className="dc-caption">Empty bins contribute zero to ECE. Changing bins changes the estimate, even though predictions are identical. Fit T on calibration data and reserve separate test data for reporting.</p></Frame>;
}
export function BellmanLab() {
 const [q,setQ]=useState(.5),[reward,setReward]=useState(1),[next,setNext]=useState(2),[gamma,setGamma]=useState(.9),[rate,setRate]=useState(.1),[ending,setEnding]=useState("continue");
 const result=tdUpdate(q,reward,next,gamma,rate,ending==="terminal");
 return <Frame title="Trace one temporal-difference update"><div className="dc-controls"><Slider label="Current Q(s,a)" value={q} set={setQ} min={-3} max={5} step={.1}/><Slider label="Reward" value={reward} set={setReward} min={-2} max={2} step={.1}/><Slider label="Maximum next Q" value={next} set={setNext} min={-3} max={5} step={.1}/><Slider label="Discount γ" value={gamma} set={setGamma} min={0} max={1} step={.01}/><Slider label="Table update rate η" value={rate} set={setRate} min={0} max={1} step={.01}/><label className="dc-control"><span>Transition type</span><select value={ending} onChange={e=>setEnding(e.target.value)}><option value="continue">Continuing transition</option><option value="terminal">True task termination</option><option value="truncated">External time-limit truncation</option></select></label></div><Readouts items={[["TD target",result.target.toFixed(4)],["TD error",result.error.toFixed(4)],["Updated table Q",result.updated.toFixed(4)]]}/><p>{ending==="terminal"?"There is no future return after true termination: the target is just the reward.":ending==="truncated"?"An external cutoff does not erase future value. Bootstrap from the actual final observation, before the environment resets.":"The target includes immediate reward plus discounted next-state value."}</p><p className="dc-caption">This is a tabular update. DQN instead takes gradient steps on a regression loss toward the detached target.</p></Frame>;
}
