import { SetsLab, StabilityLab, UncertaintyLab } from "./FoundationsLabs";

export function FoundationsChapter() {
  return <section id="foundations" className="math-chapter"><header className="math-chapter-heading"><span className="math-eyebrow">CHAPTER 03</span><h2>State the objects. Then state the claim.</h2><p>Sets tell us what belongs. Logic tells us which statements follow. These ideas sit underneath array masks, probability events, graph structures and mathematical proofs.</p></header>
    <SetsLab />
    <h3>A claim needs its quantifiers</h3><p>“For every input x, there exists a suitable model θ” permits a different model for each input. “There exists one model θ that works for every input x” asks for a single shared model. Switching ∀ and ∃ changes the problem.</p>
    <div className="math-definition-grid"><div><h4>Proof and counterexample</h4><p>A proof establishes a claim from stated assumptions. One counterexample defeats a universal claim: x = −2 refutes “x² ≥ x implies x ≥ 0.” Checking many examples is useful evidence, but does not prove a statement about all real numbers.</p></div><div><h4>Mathematical induction</h4><p>Prove a base case, then show that truth at n implies truth at n + 1. For example, 1 + … + n = n(n + 1)/2 extends by adding n + 1 to both sides. This is a proof method, distinct from statistical induction from observations.</p></div></div>
    <h3>A graph connects objects without requiring geometry</h3><p>A graph G = (V, E) has vertices V and edges E. A directed computational graph records which operations depend on which earlier values. A connected undirected graph without cycles is a tree; choosing a root gives it a hierarchy. A graph adjacency matrix and a neural weight matrix are both arrays, but their entries have different meanings.</p>
    <a className="math-source" href="https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/">Further study: MIT Mathematics for Computer Science ↗</a>
  </section>;
}

export function StatisticsChapter() {
  return <section id="statistics" className="math-chapter"><header className="math-chapter-heading"><span className="math-eyebrow">CHAPTER 09</span><h2>A sample is evidence, with uncertainty.</h2><p>Probability starts with a model and asks what observations it produces. Statistics uses observations to estimate quantities, compare explanations and assess uncertainty under assumptions.</p></header>
    <div className="math-definition-grid"><div><h4>Population and sample</h4><p>The population is the group or distribution you want to describe. A sample is what you observed. Its mean x̄ = Σxᵢ/n summarizes its center; a median is a middle ordered value and is less sensitive to extreme observations. Neither summary repairs selection bias.</p></div><div><h4>Estimator, bias and variance</h4><p>An estimator is a rule applied to a sample. Its bias is E[θ̂] − θ; its variance describes changes across repeated samples. For squared error, MSE(θ̂) = bias² + variance. These expectations are over the sampling process.</p></div></div>
    <UncertaintyLab />
    <h3>Keep the target risk separate from the sample loss</h3><div className="math-formula-block"><div>Empirical risk: R̂(f) = (1/n) Σᵢ ℓ(f(xᵢ), yᵢ)</div><div>Population risk: R(f) = E₍X,Y₎[ℓ(f(X), Y)]</div></div><p>The first is measured on particular rows. The second is an expectation under the target distribution. Fitting the first does not automatically minimize the second. A representative held-out sample estimates future performance; distribution shift can break that connection.</p>
    <div className="math-table-wrap" tabIndex={0} role="region" aria-label="Using statistical evidence"><table><thead><tr><th scope="col">Tool</th><th scope="col">What it answers</th><th scope="col">Important condition</th></tr></thead><tbody><tr><th scope="row">Confidence interval</th><td>Uncertainty from a specified repeated-sampling procedure</td><td>Sampling and model assumptions determine coverage.</td></tr><tr><th scope="row">Hypothesis test</th><td>How unusual a statistic is under a specified null model</td><td>A p-value is not the probability that the null is true. Many comparisons require error control.</td></tr><tr><th scope="row">Cross-validation</th><td>Development performance across held-out folds</td><td>Fit preprocessing inside each training fold. Use group or time splits when observations require them.</td></tr><tr><th scope="row">Final test set</th><td>An evaluation after selecting the procedure</td><td>Do not use its outcomes to select parameters or stopping times.</td></tr></tbody></table></div>
    <p>Learning theory formalizes when empirical performance transfers to population performance. PAC learning specifies error and confidence; VC dimension measures the capacity of binary hypothesis classes. These are useful next destinations in the map, with assumptions that deserve as much attention as the formulas.</p><a className="math-source" href="https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/">Further study: Understanding Machine Learning, chapters 2–6 ↗</a>
  </section>;
}

export function NumericsChapter() {
  return <section id="numerics" className="math-chapter"><header className="math-chapter-heading"><span className="math-eyebrow">CHAPTER 11</span><h2>The computer evaluates an approximation.</h2><p>Equivalent formulas can behave differently with finite precision. Separate the sensitivity of the mathematical problem from the numerical behavior of the method used to solve it.</p></header>
    <div className="math-definition-grid"><div><h4>Conditioning belongs to the problem</h4><p>An ill-conditioned problem can amplify small input perturbations even when solved carefully. For an invertible matrix, κ₂(A) = σmax(A)/σmin(A). A nearly zero smallest singular value means some information is almost lost.</p></div><div><h4>Stability belongs to the algorithm</h4><p>A numerically stable method controls the effect of rounding. Subtracting nearly equal quantities can lose relative accuracy; exponentiating a large number can overflow. A stable algorithm cannot remove a problem&apos;s inherent ill-conditioning.</p></div></div>
    <StabilityLab />
    <h3>Choose the computation as carefully as the formula</h3><ul><li><strong>Solve a system instead of explicitly inverting it.</strong> For least squares, QR or SVD often avoids the extra conditioning problems of forming XᵀX.</li><li><strong>Compute log probabilities directly.</strong> Log-sum-exp uses m + log Σ exp(zᵢ − m), with m = max zᵢ. Use fused log-loss operations when implementing a classifier.</li><li><strong>Check a derivative at several step sizes.</strong> Finite differences trade truncation error against roundoff. Reverse-mode autodiff uses vector–Jacobian products; it still operates with floating-point values.</li><li><strong>Fit scaling on training data.</strong> Reuse those statistics at evaluation. Scaling can improve conditioning but cannot guarantee a useful fit.</li></ul>
    <a className="math-source" href="https://mml-book.github.io/">Further study: Mathematics for Machine Learning ↗</a>
  </section>;
}
